"""The UCD segmentation oracle: python tests/oracle/ucd.py regen

Downloads one pinned Unicode version, then writes
  tests/oracle/ucd/GraphemeBreakTest-<v>.txt   the conformance rows, comments stripped
  tests/oracle/ucd/LineBreakTest-<v>.txt       the conformance rows, comments stripped
  src/void2d/graphemeTable.h                   Grapheme_Cluster_Break, Extended_Pictographic
                                               and Indic_Conjunct_Break, one packed range each
The gate needs none of it: the outputs are committed and src/test/ucdOracleCheck.ms reads them.
"""
import os
import sys
import tempfile
import urllib.request

VERSION = "18.0.0"
BASE = f"https://www.unicode.org/Public/{VERSION}/ucd/"
SOURCES = {
    "GraphemeBreakTest.txt": "auxiliary/GraphemeBreakTest.txt",
    "LineBreakTest.txt": "auxiliary/LineBreakTest.txt",
    "GraphemeBreakProperty.txt": "auxiliary/GraphemeBreakProperty.txt",
    "emoji-data.txt": "emoji/emoji-data.txt",
    "DerivedCoreProperties.txt": "DerivedCoreProperties.txt",
}

GCB = ["Other", "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator", "Prepend",
       "SpacingMark", "L", "V", "T", "LV", "LVT"]
INCB = ["None", "Linker", "Consonant", "Extend"]
PICTOGRAPHIC = 16
INCB_SHIFT = 5
COMPUTED = 0xFF

HANGUL_FIRST = 0xAC00
HANGUL_LAST = 0xD7A3


def fetch(directory):
    paths = {}
    for name, remote in SOURCES.items():
        path = os.path.join(directory, name)
        urllib.request.urlretrieve(BASE + remote, path)
        paths[name] = path
    return paths


def ranges(path, want):
    for line in open(path, encoding="utf-8"):
        body = line.split("#")[0].strip()
        if not body:
            continue
        fields = [f.strip() for f in body.split(";")]
        if not want(fields):
            continue
        first, _, last = fields[0].partition("..")
        yield int(first, 16), int(last or first, 16), fields


def classes(paths):
    table = {}
    for a, b, f in ranges(paths["GraphemeBreakProperty.txt"], lambda f: True):
        for c in range(a, b + 1):
            table[c] = table.get(c, 0) | GCB.index(f[1])
    extended = lambda f: f[1] == "Extended_Pictographic"
    for a, b, f in ranges(paths["emoji-data.txt"], extended):
        for c in range(a, b + 1):
            table[c] = table.get(c, 0) | PICTOGRAPHIC
    conjunct = lambda f: len(f) >= 3 and f[1] == "InCB"
    for a, b, f in ranges(paths["DerivedCoreProperties.txt"], conjunct):
        for c in range(a, b + 1):
            table[c] = table.get(c, 0) | (INCB.index(f[2]) << INCB_SHIFT)
    return table


def hangul(c):
    return GCB.index("LV") if (c - HANGUL_FIRST) % 28 == 0 else GCB.index("LVT")


def packedRanges(table):
    for c in range(HANGUL_FIRST, HANGUL_LAST + 1):
        if table.get(c, 0) != hangul(c):
            sys.exit(f"U+{c:04X} is not the Hangul syllable the lookup computes")
    starts = []
    previous = None
    for c in range(0, 0x110000):
        value = COMPUTED if HANGUL_FIRST <= c <= HANGUL_LAST else table.get(c, 0)
        if value != previous:
            starts.append((c, value))
            previous = value
    return starts


def writeTable(entries):
    lines = [
        f"// Generated by tests/oracle/ucd.py from UCD {VERSION}. Do not edit.",
        "// (start << 8) | class, sorted; a range runs to the next start. Class: bits 0-3",
        "// Grapheme_Cluster_Break, bit 4 Extended_Pictographic, bits 5-6 Indic_Conjunct_Break.",
        "// The Hangul syllables are computed, so their entry holds 0xFF.",
        "#pragma once",
        "#include <stdint.h>",
        f"#define VOID2D_GRAPHEME_RANGES {len(entries)}",
        "static const uint32_t kVoid2dGraphemeRanges[VOID2D_GRAPHEME_RANGES] = {",
    ]
    row = []
    for c, v in entries:
        row.append(f"0x{(c << 8) | v:08X}u")
        if len(row) == 6:
            lines.append("\t" + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("\t" + ", ".join(row) + ",")
    lines.append("};")
    open("src/void2d/graphemeTable.h", "w", newline="\n").write("\n".join(lines) + "\n")


def writeRows(source, name):
    out = [f"# {name}-{VERSION}.txt, the data rows of {BASE}auxiliary/{name}.txt with the"
           " comments stripped by tests/oracle/ucd.py"]
    for line in open(source, encoding="utf-8"):
        body = line.split("#")[0].strip()
        if body:
            out.append(body)
    os.makedirs("tests/oracle/ucd", exist_ok=True)
    path = f"tests/oracle/ucd/{name}-{VERSION}.txt"
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")


def regen():
    with tempfile.TemporaryDirectory() as directory:
        paths = fetch(directory)
        writeTable(packedRanges(classes(paths)))
        writeRows(paths["GraphemeBreakTest.txt"], "GraphemeBreakTest")
        writeRows(paths["LineBreakTest.txt"], "LineBreakTest")


if __name__ == "__main__":
    if sys.argv[1:] != ["regen"]:
        sys.exit("usage: python tests/oracle/ucd.py regen")
    regen()
