// Generated by scripts/regen-shaders.sh from src/void3d/programKeys.txt; do not edit.
// The programs gpu3d.c registers with the GPU door, in door order, with their keys.
#define GPU3D_PROGRAM_TABLE_LENGTH 37

static const ShaderDescription PROGRAMS[GPU3D_PROGRAM_TABLE_LENGTH] = {
	lit_program_shader_desc,
	particle_program_shader_desc,
	billboard_program_shader_desc,
	copy_program_shader_desc,
	pixelArtLit_program_shader_desc,
	pixelArtParticle_program_shader_desc,
	pixelArtBillboard_program_shader_desc,
	pixelArtPost_program_shader_desc,
	pixelArtBlit_program_shader_desc,
	litTextured_program_shader_desc,
	pixelArtLitTextured_program_shader_desc,
	unlitTextured_program_shader_desc,
	pixelArtUnlitTextured_program_shader_desc,
	litTexturedPremultiplied_program_shader_desc,
	pixelArtLitTexturedPremultiplied_program_shader_desc,
	unlitTexturedPremultiplied_program_shader_desc,
	pixelArtUnlitTexturedPremultiplied_program_shader_desc,
	litCutout_program_shader_desc,
	pixelArtLitCutout_program_shader_desc,
	litTexturedCutout_program_shader_desc,
	pixelArtLitTexturedCutout_program_shader_desc,
	unlitTexturedCutout_program_shader_desc,
	pixelArtUnlitTexturedCutout_program_shader_desc,
	shadowLit_program_shader_desc,
	shadowLitCutout_program_shader_desc,
	shadowLitTextured_program_shader_desc,
	shadowLitTexturedCutout_program_shader_desc,
	shadowUnlitTextured_program_shader_desc,
	shadowUnlitTexturedCutout_program_shader_desc,
	litShadowed_program_shader_desc,
	pixelArtLitShadowed_program_shader_desc,
	litCutoutShadowed_program_shader_desc,
	pixelArtLitCutoutShadowed_program_shader_desc,
	litTexturedShadowed_program_shader_desc,
	pixelArtLitTexturedShadowed_program_shader_desc,
	litTexturedCutoutShadowed_program_shader_desc,
	pixelArtLitTexturedCutoutShadowed_program_shader_desc,
};

static const int32_t PROGRAM_LAYOUTS[GPU3D_PROGRAM_TABLE_LENGTH] = {
	LAYOUT_LIT,
	LAYOUT_PARTICLE,
	LAYOUT_BILLBOARD,
	LAYOUT_FULLSCREEN,
	LAYOUT_LIT,
	LAYOUT_PARTICLE,
	LAYOUT_BILLBOARD,
	LAYOUT_FULLSCREEN,
	LAYOUT_FULLSCREEN,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT,
	LAYOUT_LIT,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT,
	LAYOUT_LIT,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT,
	LAYOUT_LIT,
	LAYOUT_LIT,
	LAYOUT_LIT,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
};

static const int32_t PROGRAM_KEYS[GPU3D_PROGRAM_TABLE_LENGTH] = {
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_CORE, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_PARTICLE, GPU3D_PRESET_CORE, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_BILLBOARD, GPU3D_PRESET_CORE, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_COPY, GPU3D_PRESET_CORE, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_PIXEL_ART, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_PARTICLE, GPU3D_PRESET_PIXEL_ART, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_BILLBOARD, GPU3D_PRESET_PIXEL_ART, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_POST, GPU3D_PRESET_PIXEL_ART, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_BLIT, GPU3D_PRESET_PIXEL_ART, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_CORE, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_CORE, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_CORE, 1, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 1, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_CORE, 1, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 1, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_CORE, 0, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_PIXEL_ART, 0, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_CORE, 0, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 0, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_CORE, 0, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 0, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_SHADOW, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_SHADOW, 0, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_SHADOW, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_SHADOW, 0, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_SHADOW, 0, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_SHADOW, 0, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_CORE, 0, 0, 1),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_PIXEL_ART, 0, 0, 1),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_CORE, 0, 1, 1),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_PIXEL_ART, 0, 1, 1),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_CORE, 0, 0, 1),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 0, 0, 1),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_CORE, 0, 1, 1),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 0, 1, 1),
};

_Static_assert(sizeof(particle_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_particle_vertexParams == UB_lit_vertexParams,
	"particle must take vertexParams as lit does");
_Static_assert(sizeof(billboard_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_billboard_vertexParams == UB_lit_vertexParams,
	"billboard must take vertexParams as lit does");
_Static_assert(sizeof(billboard_lightParams_t) == sizeof(lit_lightParams_t) && UB_billboard_lightParams == UB_lit_lightParams,
	"billboard must take lightParams as lit does");
_Static_assert(ATTR_pixelArtLit_program_position == ATTR_lit_program_position && ATTR_pixelArtLit_program_normal == ATTR_lit_program_normal && ATTR_pixelArtLit_program_color == ATTR_lit_program_color,
	"pixelArtLit must take the LIT layout as lit does");
_Static_assert(sizeof(pixelArtLit_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLit_modelParams == UB_lit_modelParams,
	"pixelArtLit must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLit_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLit_vertexParams == UB_lit_vertexParams,
	"pixelArtLit must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLit_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLit_lightParams == UB_lit_lightParams,
	"pixelArtLit must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLit_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLit_materialParams == UB_lit_materialParams,
	"pixelArtLit must take materialParams as lit does");
_Static_assert(ATTR_pixelArtParticle_program_root == ATTR_particle_program_root && ATTR_pixelArtParticle_program_color == ATTR_particle_program_color,
	"pixelArtParticle must take the PARTICLE layout as particle does");
_Static_assert(sizeof(pixelArtParticle_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtParticle_vertexParams == UB_lit_vertexParams,
	"pixelArtParticle must take vertexParams as lit does");
_Static_assert(ATTR_pixelArtBillboard_program_position == ATTR_billboard_program_position && ATTR_pixelArtBillboard_program_size == ATTR_billboard_program_size && ATTR_pixelArtBillboard_program_anchor == ATTR_billboard_program_anchor && ATTR_pixelArtBillboard_program_tile == ATTR_billboard_program_tile && ATTR_pixelArtBillboard_program_color == ATTR_billboard_program_color,
	"pixelArtBillboard must take the BILLBOARD layout as billboard does");
_Static_assert(sizeof(pixelArtBillboard_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtBillboard_vertexParams == UB_lit_vertexParams,
	"pixelArtBillboard must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtBillboard_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtBillboard_lightParams == UB_lit_lightParams,
	"pixelArtBillboard must take lightParams as lit does");
_Static_assert(sizeof(pixelArtBillboard_billboardParams_t) == sizeof(billboard_billboardParams_t) && UB_pixelArtBillboard_billboardParams == UB_billboard_billboardParams,
	"pixelArtBillboard must take billboardParams as billboard does");
_Static_assert(ATTR_pixelArtPost_program_position == ATTR_copy_program_position,
	"pixelArtPost must take the FULLSCREEN layout as copy does");
_Static_assert(ATTR_pixelArtBlit_program_position == ATTR_copy_program_position,
	"pixelArtBlit must take the FULLSCREEN layout as copy does");
_Static_assert(sizeof(litTextured_modelParams_t) == sizeof(lit_modelParams_t) && UB_litTextured_modelParams == UB_lit_modelParams,
	"litTextured must take modelParams as lit does");
_Static_assert(sizeof(litTextured_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_litTextured_vertexParams == UB_lit_vertexParams,
	"litTextured must take vertexParams as lit does");
_Static_assert(sizeof(litTextured_lightParams_t) == sizeof(lit_lightParams_t) && UB_litTextured_lightParams == UB_lit_lightParams,
	"litTextured must take lightParams as lit does");
_Static_assert(sizeof(litTextured_materialParams_t) == sizeof(lit_materialParams_t) && UB_litTextured_materialParams == UB_lit_materialParams,
	"litTextured must take materialParams as lit does");
_Static_assert(ATTR_pixelArtLitTextured_program_position == ATTR_litTextured_program_position && ATTR_pixelArtLitTextured_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtLitTextured_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtLitTextured_program_color == ATTR_litTextured_program_color,
	"pixelArtLitTextured must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtLitTextured_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLitTextured_modelParams == UB_lit_modelParams,
	"pixelArtLitTextured must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLitTextured_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLitTextured_vertexParams == UB_lit_vertexParams,
	"pixelArtLitTextured must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLitTextured_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLitTextured_lightParams == UB_lit_lightParams,
	"pixelArtLitTextured must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLitTextured_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLitTextured_materialParams == UB_lit_materialParams,
	"pixelArtLitTextured must take materialParams as lit does");
_Static_assert(ATTR_unlitTextured_program_position == ATTR_litTextured_program_position && ATTR_unlitTextured_program_normal == ATTR_litTextured_program_normal && ATTR_unlitTextured_program_uv == ATTR_litTextured_program_uv && ATTR_unlitTextured_program_color == ATTR_litTextured_program_color,
	"unlitTextured must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(unlitTextured_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_unlitTextured_vertexParams == UB_lit_vertexParams,
	"unlitTextured must take vertexParams as lit does");
_Static_assert(ATTR_pixelArtUnlitTextured_program_position == ATTR_litTextured_program_position && ATTR_pixelArtUnlitTextured_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtUnlitTextured_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtUnlitTextured_program_color == ATTR_litTextured_program_color,
	"pixelArtUnlitTextured must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtUnlitTextured_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtUnlitTextured_vertexParams == UB_lit_vertexParams,
	"pixelArtUnlitTextured must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtUnlitTextured_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtUnlitTextured_modelParams == UB_lit_modelParams,
	"pixelArtUnlitTextured must take modelParams as lit does");
_Static_assert(sizeof(pixelArtUnlitTextured_unlitMaterialParams_t) == sizeof(unlitTextured_unlitMaterialParams_t) && UB_pixelArtUnlitTextured_unlitMaterialParams == UB_unlitTextured_unlitMaterialParams,
	"pixelArtUnlitTextured must take unlitMaterialParams as unlitTextured does");
_Static_assert(ATTR_litTexturedPremultiplied_program_position == ATTR_litTextured_program_position && ATTR_litTexturedPremultiplied_program_normal == ATTR_litTextured_program_normal && ATTR_litTexturedPremultiplied_program_uv == ATTR_litTextured_program_uv && ATTR_litTexturedPremultiplied_program_color == ATTR_litTextured_program_color,
	"litTexturedPremultiplied must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(litTexturedPremultiplied_modelParams_t) == sizeof(lit_modelParams_t) && UB_litTexturedPremultiplied_modelParams == UB_lit_modelParams,
	"litTexturedPremultiplied must take modelParams as lit does");
_Static_assert(sizeof(litTexturedPremultiplied_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_litTexturedPremultiplied_vertexParams == UB_lit_vertexParams,
	"litTexturedPremultiplied must take vertexParams as lit does");
_Static_assert(sizeof(litTexturedPremultiplied_lightParams_t) == sizeof(lit_lightParams_t) && UB_litTexturedPremultiplied_lightParams == UB_lit_lightParams,
	"litTexturedPremultiplied must take lightParams as lit does");
_Static_assert(sizeof(litTexturedPremultiplied_materialParams_t) == sizeof(lit_materialParams_t) && UB_litTexturedPremultiplied_materialParams == UB_lit_materialParams,
	"litTexturedPremultiplied must take materialParams as lit does");
_Static_assert(ATTR_pixelArtLitTexturedPremultiplied_program_position == ATTR_litTextured_program_position && ATTR_pixelArtLitTexturedPremultiplied_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtLitTexturedPremultiplied_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtLitTexturedPremultiplied_program_color == ATTR_litTextured_program_color,
	"pixelArtLitTexturedPremultiplied must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtLitTexturedPremultiplied_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLitTexturedPremultiplied_modelParams == UB_lit_modelParams,
	"pixelArtLitTexturedPremultiplied must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedPremultiplied_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLitTexturedPremultiplied_vertexParams == UB_lit_vertexParams,
	"pixelArtLitTexturedPremultiplied must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedPremultiplied_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLitTexturedPremultiplied_lightParams == UB_lit_lightParams,
	"pixelArtLitTexturedPremultiplied must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedPremultiplied_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLitTexturedPremultiplied_materialParams == UB_lit_materialParams,
	"pixelArtLitTexturedPremultiplied must take materialParams as lit does");
_Static_assert(ATTR_unlitTexturedPremultiplied_program_position == ATTR_litTextured_program_position && ATTR_unlitTexturedPremultiplied_program_normal == ATTR_litTextured_program_normal && ATTR_unlitTexturedPremultiplied_program_uv == ATTR_litTextured_program_uv && ATTR_unlitTexturedPremultiplied_program_color == ATTR_litTextured_program_color,
	"unlitTexturedPremultiplied must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(unlitTexturedPremultiplied_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_unlitTexturedPremultiplied_vertexParams == UB_lit_vertexParams,
	"unlitTexturedPremultiplied must take vertexParams as lit does");
_Static_assert(sizeof(unlitTexturedPremultiplied_modelTransformParams_t) == sizeof(unlitTextured_modelTransformParams_t) && UB_unlitTexturedPremultiplied_modelTransformParams == UB_unlitTextured_modelTransformParams,
	"unlitTexturedPremultiplied must take modelTransformParams as unlitTextured does");
_Static_assert(sizeof(unlitTexturedPremultiplied_unlitMaterialParams_t) == sizeof(unlitTextured_unlitMaterialParams_t) && UB_unlitTexturedPremultiplied_unlitMaterialParams == UB_unlitTextured_unlitMaterialParams,
	"unlitTexturedPremultiplied must take unlitMaterialParams as unlitTextured does");
_Static_assert(ATTR_pixelArtUnlitTexturedPremultiplied_program_position == ATTR_litTextured_program_position && ATTR_pixelArtUnlitTexturedPremultiplied_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtUnlitTexturedPremultiplied_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtUnlitTexturedPremultiplied_program_color == ATTR_litTextured_program_color,
	"pixelArtUnlitTexturedPremultiplied must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtUnlitTexturedPremultiplied_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtUnlitTexturedPremultiplied_vertexParams == UB_lit_vertexParams,
	"pixelArtUnlitTexturedPremultiplied must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtUnlitTexturedPremultiplied_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtUnlitTexturedPremultiplied_modelParams == UB_lit_modelParams,
	"pixelArtUnlitTexturedPremultiplied must take modelParams as lit does");
_Static_assert(sizeof(pixelArtUnlitTexturedPremultiplied_unlitMaterialParams_t) == sizeof(unlitTextured_unlitMaterialParams_t) && UB_pixelArtUnlitTexturedPremultiplied_unlitMaterialParams == UB_unlitTextured_unlitMaterialParams,
	"pixelArtUnlitTexturedPremultiplied must take unlitMaterialParams as unlitTextured does");
_Static_assert(ATTR_litCutout_program_position == ATTR_lit_program_position && ATTR_litCutout_program_normal == ATTR_lit_program_normal && ATTR_litCutout_program_color == ATTR_lit_program_color,
	"litCutout must take the LIT layout as lit does");
_Static_assert(sizeof(litCutout_modelParams_t) == sizeof(lit_modelParams_t) && UB_litCutout_modelParams == UB_lit_modelParams,
	"litCutout must take modelParams as lit does");
_Static_assert(sizeof(litCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_litCutout_vertexParams == UB_lit_vertexParams,
	"litCutout must take vertexParams as lit does");
_Static_assert(sizeof(litCutout_lightParams_t) == sizeof(lit_lightParams_t) && UB_litCutout_lightParams == UB_lit_lightParams,
	"litCutout must take lightParams as lit does");
_Static_assert(sizeof(litCutout_materialParams_t) == sizeof(lit_materialParams_t) && UB_litCutout_materialParams == UB_lit_materialParams,
	"litCutout must take materialParams as lit does");
_Static_assert(ATTR_pixelArtLitCutout_program_position == ATTR_lit_program_position && ATTR_pixelArtLitCutout_program_normal == ATTR_lit_program_normal && ATTR_pixelArtLitCutout_program_color == ATTR_lit_program_color,
	"pixelArtLitCutout must take the LIT layout as lit does");
_Static_assert(sizeof(pixelArtLitCutout_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLitCutout_modelParams == UB_lit_modelParams,
	"pixelArtLitCutout must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLitCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLitCutout_vertexParams == UB_lit_vertexParams,
	"pixelArtLitCutout must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLitCutout_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLitCutout_lightParams == UB_lit_lightParams,
	"pixelArtLitCutout must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLitCutout_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLitCutout_materialParams == UB_lit_materialParams,
	"pixelArtLitCutout must take materialParams as lit does");
_Static_assert(ATTR_litTexturedCutout_program_position == ATTR_litTextured_program_position && ATTR_litTexturedCutout_program_normal == ATTR_litTextured_program_normal && ATTR_litTexturedCutout_program_uv == ATTR_litTextured_program_uv && ATTR_litTexturedCutout_program_color == ATTR_litTextured_program_color,
	"litTexturedCutout must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(litTexturedCutout_modelParams_t) == sizeof(lit_modelParams_t) && UB_litTexturedCutout_modelParams == UB_lit_modelParams,
	"litTexturedCutout must take modelParams as lit does");
_Static_assert(sizeof(litTexturedCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_litTexturedCutout_vertexParams == UB_lit_vertexParams,
	"litTexturedCutout must take vertexParams as lit does");
_Static_assert(sizeof(litTexturedCutout_lightParams_t) == sizeof(lit_lightParams_t) && UB_litTexturedCutout_lightParams == UB_lit_lightParams,
	"litTexturedCutout must take lightParams as lit does");
_Static_assert(sizeof(litTexturedCutout_materialParams_t) == sizeof(lit_materialParams_t) && UB_litTexturedCutout_materialParams == UB_lit_materialParams,
	"litTexturedCutout must take materialParams as lit does");
_Static_assert(ATTR_pixelArtLitTexturedCutout_program_position == ATTR_litTextured_program_position && ATTR_pixelArtLitTexturedCutout_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtLitTexturedCutout_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtLitTexturedCutout_program_color == ATTR_litTextured_program_color,
	"pixelArtLitTexturedCutout must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtLitTexturedCutout_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLitTexturedCutout_modelParams == UB_lit_modelParams,
	"pixelArtLitTexturedCutout must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLitTexturedCutout_vertexParams == UB_lit_vertexParams,
	"pixelArtLitTexturedCutout must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedCutout_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLitTexturedCutout_lightParams == UB_lit_lightParams,
	"pixelArtLitTexturedCutout must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedCutout_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLitTexturedCutout_materialParams == UB_lit_materialParams,
	"pixelArtLitTexturedCutout must take materialParams as lit does");
_Static_assert(ATTR_unlitTexturedCutout_program_position == ATTR_litTextured_program_position && ATTR_unlitTexturedCutout_program_normal == ATTR_litTextured_program_normal && ATTR_unlitTexturedCutout_program_uv == ATTR_litTextured_program_uv && ATTR_unlitTexturedCutout_program_color == ATTR_litTextured_program_color,
	"unlitTexturedCutout must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(unlitTexturedCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_unlitTexturedCutout_vertexParams == UB_lit_vertexParams,
	"unlitTexturedCutout must take vertexParams as lit does");
_Static_assert(sizeof(unlitTexturedCutout_modelTransformParams_t) == sizeof(unlitTextured_modelTransformParams_t) && UB_unlitTexturedCutout_modelTransformParams == UB_unlitTextured_modelTransformParams,
	"unlitTexturedCutout must take modelTransformParams as unlitTextured does");
_Static_assert(sizeof(unlitTexturedCutout_unlitMaterialParams_t) == sizeof(unlitTextured_unlitMaterialParams_t) && UB_unlitTexturedCutout_unlitMaterialParams == UB_unlitTextured_unlitMaterialParams,
	"unlitTexturedCutout must take unlitMaterialParams as unlitTextured does");
_Static_assert(ATTR_pixelArtUnlitTexturedCutout_program_position == ATTR_litTextured_program_position && ATTR_pixelArtUnlitTexturedCutout_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtUnlitTexturedCutout_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtUnlitTexturedCutout_program_color == ATTR_litTextured_program_color,
	"pixelArtUnlitTexturedCutout must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtUnlitTexturedCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtUnlitTexturedCutout_vertexParams == UB_lit_vertexParams,
	"pixelArtUnlitTexturedCutout must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtUnlitTexturedCutout_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtUnlitTexturedCutout_modelParams == UB_lit_modelParams,
	"pixelArtUnlitTexturedCutout must take modelParams as lit does");
_Static_assert(sizeof(pixelArtUnlitTexturedCutout_unlitMaterialParams_t) == sizeof(unlitTextured_unlitMaterialParams_t) && UB_pixelArtUnlitTexturedCutout_unlitMaterialParams == UB_unlitTextured_unlitMaterialParams,
	"pixelArtUnlitTexturedCutout must take unlitMaterialParams as unlitTextured does");
_Static_assert(ATTR_shadowLit_program_position == ATTR_lit_program_position && ATTR_shadowLit_program_normal == ATTR_lit_program_normal && ATTR_shadowLit_program_color == ATTR_lit_program_color,
	"shadowLit must take the LIT layout as lit does");
_Static_assert(sizeof(shadowLit_modelParams_t) == sizeof(lit_modelParams_t) && UB_shadowLit_modelParams == UB_lit_modelParams,
	"shadowLit must take modelParams as lit does");
_Static_assert(sizeof(shadowLit_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_shadowLit_vertexParams == UB_lit_vertexParams,
	"shadowLit must take vertexParams as lit does");
_Static_assert(ATTR_shadowLitCutout_program_position == ATTR_lit_program_position && ATTR_shadowLitCutout_program_normal == ATTR_lit_program_normal && ATTR_shadowLitCutout_program_color == ATTR_lit_program_color,
	"shadowLitCutout must take the LIT layout as lit does");
_Static_assert(sizeof(shadowLitCutout_modelParams_t) == sizeof(lit_modelParams_t) && UB_shadowLitCutout_modelParams == UB_lit_modelParams,
	"shadowLitCutout must take modelParams as lit does");
_Static_assert(sizeof(shadowLitCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_shadowLitCutout_vertexParams == UB_lit_vertexParams,
	"shadowLitCutout must take vertexParams as lit does");
_Static_assert(sizeof(shadowLitCutout_materialParams_t) == sizeof(lit_materialParams_t) && UB_shadowLitCutout_materialParams == UB_lit_materialParams,
	"shadowLitCutout must take materialParams as lit does");
_Static_assert(ATTR_shadowLitTextured_program_position == ATTR_litTextured_program_position && ATTR_shadowLitTextured_program_normal == ATTR_litTextured_program_normal && ATTR_shadowLitTextured_program_uv == ATTR_litTextured_program_uv && ATTR_shadowLitTextured_program_color == ATTR_litTextured_program_color,
	"shadowLitTextured must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(shadowLitTextured_modelParams_t) == sizeof(lit_modelParams_t) && UB_shadowLitTextured_modelParams == UB_lit_modelParams,
	"shadowLitTextured must take modelParams as lit does");
_Static_assert(sizeof(shadowLitTextured_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_shadowLitTextured_vertexParams == UB_lit_vertexParams,
	"shadowLitTextured must take vertexParams as lit does");
_Static_assert(ATTR_shadowLitTexturedCutout_program_position == ATTR_litTextured_program_position && ATTR_shadowLitTexturedCutout_program_normal == ATTR_litTextured_program_normal && ATTR_shadowLitTexturedCutout_program_uv == ATTR_litTextured_program_uv && ATTR_shadowLitTexturedCutout_program_color == ATTR_litTextured_program_color,
	"shadowLitTexturedCutout must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(shadowLitTexturedCutout_modelParams_t) == sizeof(lit_modelParams_t) && UB_shadowLitTexturedCutout_modelParams == UB_lit_modelParams,
	"shadowLitTexturedCutout must take modelParams as lit does");
_Static_assert(sizeof(shadowLitTexturedCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_shadowLitTexturedCutout_vertexParams == UB_lit_vertexParams,
	"shadowLitTexturedCutout must take vertexParams as lit does");
_Static_assert(sizeof(shadowLitTexturedCutout_materialParams_t) == sizeof(lit_materialParams_t) && UB_shadowLitTexturedCutout_materialParams == UB_lit_materialParams,
	"shadowLitTexturedCutout must take materialParams as lit does");
_Static_assert(ATTR_shadowUnlitTextured_program_position == ATTR_litTextured_program_position && ATTR_shadowUnlitTextured_program_normal == ATTR_litTextured_program_normal && ATTR_shadowUnlitTextured_program_uv == ATTR_litTextured_program_uv && ATTR_shadowUnlitTextured_program_color == ATTR_litTextured_program_color,
	"shadowUnlitTextured must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(shadowUnlitTextured_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_shadowUnlitTextured_vertexParams == UB_lit_vertexParams,
	"shadowUnlitTextured must take vertexParams as lit does");
_Static_assert(sizeof(shadowUnlitTextured_modelTransformParams_t) == sizeof(unlitTextured_modelTransformParams_t) && UB_shadowUnlitTextured_modelTransformParams == UB_unlitTextured_modelTransformParams,
	"shadowUnlitTextured must take modelTransformParams as unlitTextured does");
_Static_assert(ATTR_shadowUnlitTexturedCutout_program_position == ATTR_litTextured_program_position && ATTR_shadowUnlitTexturedCutout_program_normal == ATTR_litTextured_program_normal && ATTR_shadowUnlitTexturedCutout_program_uv == ATTR_litTextured_program_uv && ATTR_shadowUnlitTexturedCutout_program_color == ATTR_litTextured_program_color,
	"shadowUnlitTexturedCutout must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(shadowUnlitTexturedCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_shadowUnlitTexturedCutout_vertexParams == UB_lit_vertexParams,
	"shadowUnlitTexturedCutout must take vertexParams as lit does");
_Static_assert(sizeof(shadowUnlitTexturedCutout_modelTransformParams_t) == sizeof(unlitTextured_modelTransformParams_t) && UB_shadowUnlitTexturedCutout_modelTransformParams == UB_unlitTextured_modelTransformParams,
	"shadowUnlitTexturedCutout must take modelTransformParams as unlitTextured does");
_Static_assert(sizeof(shadowUnlitTexturedCutout_unlitMaterialParams_t) == sizeof(unlitTextured_unlitMaterialParams_t) && UB_shadowUnlitTexturedCutout_unlitMaterialParams == UB_unlitTextured_unlitMaterialParams,
	"shadowUnlitTexturedCutout must take unlitMaterialParams as unlitTextured does");
_Static_assert(ATTR_litShadowed_program_position == ATTR_lit_program_position && ATTR_litShadowed_program_normal == ATTR_lit_program_normal && ATTR_litShadowed_program_color == ATTR_lit_program_color,
	"litShadowed must take the LIT layout as lit does");
_Static_assert(sizeof(litShadowed_modelParams_t) == sizeof(lit_modelParams_t) && UB_litShadowed_modelParams == UB_lit_modelParams,
	"litShadowed must take modelParams as lit does");
_Static_assert(sizeof(litShadowed_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_litShadowed_vertexParams == UB_lit_vertexParams,
	"litShadowed must take vertexParams as lit does");
_Static_assert(sizeof(litShadowed_lightParams_t) == sizeof(lit_lightParams_t) && UB_litShadowed_lightParams == UB_lit_lightParams,
	"litShadowed must take lightParams as lit does");
_Static_assert(sizeof(litShadowed_materialParams_t) == sizeof(lit_materialParams_t) && UB_litShadowed_materialParams == UB_lit_materialParams,
	"litShadowed must take materialParams as lit does");
_Static_assert(ATTR_pixelArtLitShadowed_program_position == ATTR_lit_program_position && ATTR_pixelArtLitShadowed_program_normal == ATTR_lit_program_normal && ATTR_pixelArtLitShadowed_program_color == ATTR_lit_program_color,
	"pixelArtLitShadowed must take the LIT layout as lit does");
_Static_assert(sizeof(pixelArtLitShadowed_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLitShadowed_modelParams == UB_lit_modelParams,
	"pixelArtLitShadowed must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLitShadowed_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLitShadowed_vertexParams == UB_lit_vertexParams,
	"pixelArtLitShadowed must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLitShadowed_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLitShadowed_lightParams == UB_lit_lightParams,
	"pixelArtLitShadowed must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLitShadowed_shadowParams_t) == sizeof(litShadowed_shadowParams_t) && UB_pixelArtLitShadowed_shadowParams == UB_litShadowed_shadowParams,
	"pixelArtLitShadowed must take shadowParams as litShadowed does");
_Static_assert(sizeof(pixelArtLitShadowed_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLitShadowed_materialParams == UB_lit_materialParams,
	"pixelArtLitShadowed must take materialParams as lit does");
_Static_assert(ATTR_litCutoutShadowed_program_position == ATTR_lit_program_position && ATTR_litCutoutShadowed_program_normal == ATTR_lit_program_normal && ATTR_litCutoutShadowed_program_color == ATTR_lit_program_color,
	"litCutoutShadowed must take the LIT layout as lit does");
_Static_assert(sizeof(litCutoutShadowed_modelParams_t) == sizeof(lit_modelParams_t) && UB_litCutoutShadowed_modelParams == UB_lit_modelParams,
	"litCutoutShadowed must take modelParams as lit does");
_Static_assert(sizeof(litCutoutShadowed_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_litCutoutShadowed_vertexParams == UB_lit_vertexParams,
	"litCutoutShadowed must take vertexParams as lit does");
_Static_assert(sizeof(litCutoutShadowed_lightParams_t) == sizeof(lit_lightParams_t) && UB_litCutoutShadowed_lightParams == UB_lit_lightParams,
	"litCutoutShadowed must take lightParams as lit does");
_Static_assert(sizeof(litCutoutShadowed_shadowParams_t) == sizeof(litShadowed_shadowParams_t) && UB_litCutoutShadowed_shadowParams == UB_litShadowed_shadowParams,
	"litCutoutShadowed must take shadowParams as litShadowed does");
_Static_assert(sizeof(litCutoutShadowed_materialParams_t) == sizeof(lit_materialParams_t) && UB_litCutoutShadowed_materialParams == UB_lit_materialParams,
	"litCutoutShadowed must take materialParams as lit does");
_Static_assert(ATTR_pixelArtLitCutoutShadowed_program_position == ATTR_lit_program_position && ATTR_pixelArtLitCutoutShadowed_program_normal == ATTR_lit_program_normal && ATTR_pixelArtLitCutoutShadowed_program_color == ATTR_lit_program_color,
	"pixelArtLitCutoutShadowed must take the LIT layout as lit does");
_Static_assert(sizeof(pixelArtLitCutoutShadowed_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLitCutoutShadowed_modelParams == UB_lit_modelParams,
	"pixelArtLitCutoutShadowed must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLitCutoutShadowed_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLitCutoutShadowed_vertexParams == UB_lit_vertexParams,
	"pixelArtLitCutoutShadowed must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLitCutoutShadowed_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLitCutoutShadowed_lightParams == UB_lit_lightParams,
	"pixelArtLitCutoutShadowed must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLitCutoutShadowed_shadowParams_t) == sizeof(litShadowed_shadowParams_t) && UB_pixelArtLitCutoutShadowed_shadowParams == UB_litShadowed_shadowParams,
	"pixelArtLitCutoutShadowed must take shadowParams as litShadowed does");
_Static_assert(sizeof(pixelArtLitCutoutShadowed_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLitCutoutShadowed_materialParams == UB_lit_materialParams,
	"pixelArtLitCutoutShadowed must take materialParams as lit does");
_Static_assert(ATTR_litTexturedShadowed_program_position == ATTR_litTextured_program_position && ATTR_litTexturedShadowed_program_normal == ATTR_litTextured_program_normal && ATTR_litTexturedShadowed_program_uv == ATTR_litTextured_program_uv && ATTR_litTexturedShadowed_program_color == ATTR_litTextured_program_color,
	"litTexturedShadowed must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(litTexturedShadowed_modelParams_t) == sizeof(lit_modelParams_t) && UB_litTexturedShadowed_modelParams == UB_lit_modelParams,
	"litTexturedShadowed must take modelParams as lit does");
_Static_assert(sizeof(litTexturedShadowed_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_litTexturedShadowed_vertexParams == UB_lit_vertexParams,
	"litTexturedShadowed must take vertexParams as lit does");
_Static_assert(sizeof(litTexturedShadowed_lightParams_t) == sizeof(lit_lightParams_t) && UB_litTexturedShadowed_lightParams == UB_lit_lightParams,
	"litTexturedShadowed must take lightParams as lit does");
_Static_assert(sizeof(litTexturedShadowed_shadowParams_t) == sizeof(litShadowed_shadowParams_t) && UB_litTexturedShadowed_shadowParams == UB_litShadowed_shadowParams,
	"litTexturedShadowed must take shadowParams as litShadowed does");
_Static_assert(sizeof(litTexturedShadowed_materialParams_t) == sizeof(lit_materialParams_t) && UB_litTexturedShadowed_materialParams == UB_lit_materialParams,
	"litTexturedShadowed must take materialParams as lit does");
_Static_assert(ATTR_pixelArtLitTexturedShadowed_program_position == ATTR_litTextured_program_position && ATTR_pixelArtLitTexturedShadowed_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtLitTexturedShadowed_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtLitTexturedShadowed_program_color == ATTR_litTextured_program_color,
	"pixelArtLitTexturedShadowed must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtLitTexturedShadowed_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLitTexturedShadowed_modelParams == UB_lit_modelParams,
	"pixelArtLitTexturedShadowed must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedShadowed_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLitTexturedShadowed_vertexParams == UB_lit_vertexParams,
	"pixelArtLitTexturedShadowed must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedShadowed_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLitTexturedShadowed_lightParams == UB_lit_lightParams,
	"pixelArtLitTexturedShadowed must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedShadowed_shadowParams_t) == sizeof(litShadowed_shadowParams_t) && UB_pixelArtLitTexturedShadowed_shadowParams == UB_litShadowed_shadowParams,
	"pixelArtLitTexturedShadowed must take shadowParams as litShadowed does");
_Static_assert(sizeof(pixelArtLitTexturedShadowed_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLitTexturedShadowed_materialParams == UB_lit_materialParams,
	"pixelArtLitTexturedShadowed must take materialParams as lit does");
_Static_assert(ATTR_litTexturedCutoutShadowed_program_position == ATTR_litTextured_program_position && ATTR_litTexturedCutoutShadowed_program_normal == ATTR_litTextured_program_normal && ATTR_litTexturedCutoutShadowed_program_uv == ATTR_litTextured_program_uv && ATTR_litTexturedCutoutShadowed_program_color == ATTR_litTextured_program_color,
	"litTexturedCutoutShadowed must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(litTexturedCutoutShadowed_modelParams_t) == sizeof(lit_modelParams_t) && UB_litTexturedCutoutShadowed_modelParams == UB_lit_modelParams,
	"litTexturedCutoutShadowed must take modelParams as lit does");
_Static_assert(sizeof(litTexturedCutoutShadowed_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_litTexturedCutoutShadowed_vertexParams == UB_lit_vertexParams,
	"litTexturedCutoutShadowed must take vertexParams as lit does");
_Static_assert(sizeof(litTexturedCutoutShadowed_lightParams_t) == sizeof(lit_lightParams_t) && UB_litTexturedCutoutShadowed_lightParams == UB_lit_lightParams,
	"litTexturedCutoutShadowed must take lightParams as lit does");
_Static_assert(sizeof(litTexturedCutoutShadowed_shadowParams_t) == sizeof(litShadowed_shadowParams_t) && UB_litTexturedCutoutShadowed_shadowParams == UB_litShadowed_shadowParams,
	"litTexturedCutoutShadowed must take shadowParams as litShadowed does");
_Static_assert(sizeof(litTexturedCutoutShadowed_materialParams_t) == sizeof(lit_materialParams_t) && UB_litTexturedCutoutShadowed_materialParams == UB_lit_materialParams,
	"litTexturedCutoutShadowed must take materialParams as lit does");
_Static_assert(ATTR_pixelArtLitTexturedCutoutShadowed_program_position == ATTR_litTextured_program_position && ATTR_pixelArtLitTexturedCutoutShadowed_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtLitTexturedCutoutShadowed_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtLitTexturedCutoutShadowed_program_color == ATTR_litTextured_program_color,
	"pixelArtLitTexturedCutoutShadowed must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtLitTexturedCutoutShadowed_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLitTexturedCutoutShadowed_modelParams == UB_lit_modelParams,
	"pixelArtLitTexturedCutoutShadowed must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedCutoutShadowed_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLitTexturedCutoutShadowed_vertexParams == UB_lit_vertexParams,
	"pixelArtLitTexturedCutoutShadowed must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedCutoutShadowed_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLitTexturedCutoutShadowed_lightParams == UB_lit_lightParams,
	"pixelArtLitTexturedCutoutShadowed must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedCutoutShadowed_shadowParams_t) == sizeof(litShadowed_shadowParams_t) && UB_pixelArtLitTexturedCutoutShadowed_shadowParams == UB_litShadowed_shadowParams,
	"pixelArtLitTexturedCutoutShadowed must take shadowParams as litShadowed does");
_Static_assert(sizeof(pixelArtLitTexturedCutoutShadowed_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLitTexturedCutoutShadowed_materialParams == UB_lit_materialParams,
	"pixelArtLitTexturedCutoutShadowed must take materialParams as lit does");
