// Generated by scripts/regen-shaders.sh from src/void3d/programKeys.txt; do not edit.
// The programs gpu3d.c registers with the GPU door, in door order, with their keys.
#define GPU3D_PROGRAM_TABLE_LENGTH 23

static const ShaderDescription PROGRAMS[GPU3D_PROGRAM_TABLE_LENGTH] = {
	lit_program_shader_desc,
	particle_program_shader_desc,
	billboard_program_shader_desc,
	copy_program_shader_desc,
	pixelArtLit_program_shader_desc,
	pixelArtParticle_program_shader_desc,
	pixelArtBillboard_program_shader_desc,
	pixelArtPost_program_shader_desc,
	pixelArtBlit_program_shader_desc,
	litTextured_program_shader_desc,
	pixelArtLitTextured_program_shader_desc,
	unlitTextured_program_shader_desc,
	pixelArtUnlitTextured_program_shader_desc,
	litTexturedPremultiplied_program_shader_desc,
	pixelArtLitTexturedPremultiplied_program_shader_desc,
	unlitTexturedPremultiplied_program_shader_desc,
	pixelArtUnlitTexturedPremultiplied_program_shader_desc,
	litCutout_program_shader_desc,
	pixelArtLitCutout_program_shader_desc,
	litTexturedCutout_program_shader_desc,
	pixelArtLitTexturedCutout_program_shader_desc,
	unlitTexturedCutout_program_shader_desc,
	pixelArtUnlitTexturedCutout_program_shader_desc,
};

static const int32_t PROGRAM_LAYOUTS[GPU3D_PROGRAM_TABLE_LENGTH] = {
	LAYOUT_LIT,
	LAYOUT_PARTICLE,
	LAYOUT_BILLBOARD,
	LAYOUT_FULLSCREEN,
	LAYOUT_LIT,
	LAYOUT_PARTICLE,
	LAYOUT_BILLBOARD,
	LAYOUT_FULLSCREEN,
	LAYOUT_FULLSCREEN,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT,
	LAYOUT_LIT,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
	LAYOUT_LIT_TEXTURED,
};

static const int32_t PROGRAM_KEYS[GPU3D_PROGRAM_TABLE_LENGTH] = {
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_CORE, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_PARTICLE, GPU3D_PRESET_CORE, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_BILLBOARD, GPU3D_PRESET_CORE, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_COPY, GPU3D_PRESET_CORE, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_PIXEL_ART, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_PARTICLE, GPU3D_PRESET_PIXEL_ART, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_BILLBOARD, GPU3D_PRESET_PIXEL_ART, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_POST, GPU3D_PRESET_PIXEL_ART, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_BLIT, GPU3D_PRESET_PIXEL_ART, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_CORE, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_CORE, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 0, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_CORE, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_CORE, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 1, 0),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_CORE, 0, 1),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT, GPU3D_PRESET_PIXEL_ART, 0, 1),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_CORE, 0, 1),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_LIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 0, 1),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_CORE, 0, 1),
	GPU3D_PROGRAM_KEY(GPU3D_PROGRAM_UNLIT_TEXTURED, GPU3D_PRESET_PIXEL_ART, 0, 1),
};

_Static_assert(sizeof(particle_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_particle_vertexParams == UB_lit_vertexParams,
	"particle must take vertexParams as lit does");
_Static_assert(sizeof(billboard_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_billboard_vertexParams == UB_lit_vertexParams,
	"billboard must take vertexParams as lit does");
_Static_assert(sizeof(billboard_lightParams_t) == sizeof(lit_lightParams_t) && UB_billboard_lightParams == UB_lit_lightParams,
	"billboard must take lightParams as lit does");
_Static_assert(ATTR_pixelArtLit_program_position == ATTR_lit_program_position && ATTR_pixelArtLit_program_normal == ATTR_lit_program_normal && ATTR_pixelArtLit_program_color == ATTR_lit_program_color,
	"pixelArtLit must take the LIT layout as lit does");
_Static_assert(sizeof(pixelArtLit_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLit_modelParams == UB_lit_modelParams,
	"pixelArtLit must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLit_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLit_vertexParams == UB_lit_vertexParams,
	"pixelArtLit must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLit_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLit_lightParams == UB_lit_lightParams,
	"pixelArtLit must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLit_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLit_materialParams == UB_lit_materialParams,
	"pixelArtLit must take materialParams as lit does");
_Static_assert(ATTR_pixelArtParticle_program_root == ATTR_particle_program_root && ATTR_pixelArtParticle_program_color == ATTR_particle_program_color,
	"pixelArtParticle must take the PARTICLE layout as particle does");
_Static_assert(sizeof(pixelArtParticle_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtParticle_vertexParams == UB_lit_vertexParams,
	"pixelArtParticle must take vertexParams as lit does");
_Static_assert(ATTR_pixelArtBillboard_program_position == ATTR_billboard_program_position && ATTR_pixelArtBillboard_program_size == ATTR_billboard_program_size && ATTR_pixelArtBillboard_program_anchor == ATTR_billboard_program_anchor && ATTR_pixelArtBillboard_program_tile == ATTR_billboard_program_tile && ATTR_pixelArtBillboard_program_color == ATTR_billboard_program_color,
	"pixelArtBillboard must take the BILLBOARD layout as billboard does");
_Static_assert(sizeof(pixelArtBillboard_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtBillboard_vertexParams == UB_lit_vertexParams,
	"pixelArtBillboard must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtBillboard_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtBillboard_lightParams == UB_lit_lightParams,
	"pixelArtBillboard must take lightParams as lit does");
_Static_assert(sizeof(pixelArtBillboard_billboardParams_t) == sizeof(billboard_billboardParams_t) && UB_pixelArtBillboard_billboardParams == UB_billboard_billboardParams,
	"pixelArtBillboard must take billboardParams as billboard does");
_Static_assert(ATTR_pixelArtPost_program_position == ATTR_copy_program_position,
	"pixelArtPost must take the FULLSCREEN layout as copy does");
_Static_assert(ATTR_pixelArtBlit_program_position == ATTR_copy_program_position,
	"pixelArtBlit must take the FULLSCREEN layout as copy does");
_Static_assert(sizeof(litTextured_modelParams_t) == sizeof(lit_modelParams_t) && UB_litTextured_modelParams == UB_lit_modelParams,
	"litTextured must take modelParams as lit does");
_Static_assert(sizeof(litTextured_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_litTextured_vertexParams == UB_lit_vertexParams,
	"litTextured must take vertexParams as lit does");
_Static_assert(sizeof(litTextured_lightParams_t) == sizeof(lit_lightParams_t) && UB_litTextured_lightParams == UB_lit_lightParams,
	"litTextured must take lightParams as lit does");
_Static_assert(sizeof(litTextured_materialParams_t) == sizeof(lit_materialParams_t) && UB_litTextured_materialParams == UB_lit_materialParams,
	"litTextured must take materialParams as lit does");
_Static_assert(ATTR_pixelArtLitTextured_program_position == ATTR_litTextured_program_position && ATTR_pixelArtLitTextured_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtLitTextured_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtLitTextured_program_color == ATTR_litTextured_program_color,
	"pixelArtLitTextured must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtLitTextured_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLitTextured_modelParams == UB_lit_modelParams,
	"pixelArtLitTextured must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLitTextured_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLitTextured_vertexParams == UB_lit_vertexParams,
	"pixelArtLitTextured must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLitTextured_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLitTextured_lightParams == UB_lit_lightParams,
	"pixelArtLitTextured must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLitTextured_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLitTextured_materialParams == UB_lit_materialParams,
	"pixelArtLitTextured must take materialParams as lit does");
_Static_assert(ATTR_unlitTextured_program_position == ATTR_litTextured_program_position && ATTR_unlitTextured_program_normal == ATTR_litTextured_program_normal && ATTR_unlitTextured_program_uv == ATTR_litTextured_program_uv && ATTR_unlitTextured_program_color == ATTR_litTextured_program_color,
	"unlitTextured must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(unlitTextured_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_unlitTextured_vertexParams == UB_lit_vertexParams,
	"unlitTextured must take vertexParams as lit does");
_Static_assert(ATTR_pixelArtUnlitTextured_program_position == ATTR_litTextured_program_position && ATTR_pixelArtUnlitTextured_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtUnlitTextured_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtUnlitTextured_program_color == ATTR_litTextured_program_color,
	"pixelArtUnlitTextured must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtUnlitTextured_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtUnlitTextured_vertexParams == UB_lit_vertexParams,
	"pixelArtUnlitTextured must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtUnlitTextured_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtUnlitTextured_modelParams == UB_lit_modelParams,
	"pixelArtUnlitTextured must take modelParams as lit does");
_Static_assert(sizeof(pixelArtUnlitTextured_unlitMaterialParams_t) == sizeof(unlitTextured_unlitMaterialParams_t) && UB_pixelArtUnlitTextured_unlitMaterialParams == UB_unlitTextured_unlitMaterialParams,
	"pixelArtUnlitTextured must take unlitMaterialParams as unlitTextured does");
_Static_assert(ATTR_litTexturedPremultiplied_program_position == ATTR_litTextured_program_position && ATTR_litTexturedPremultiplied_program_normal == ATTR_litTextured_program_normal && ATTR_litTexturedPremultiplied_program_uv == ATTR_litTextured_program_uv && ATTR_litTexturedPremultiplied_program_color == ATTR_litTextured_program_color,
	"litTexturedPremultiplied must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(litTexturedPremultiplied_modelParams_t) == sizeof(lit_modelParams_t) && UB_litTexturedPremultiplied_modelParams == UB_lit_modelParams,
	"litTexturedPremultiplied must take modelParams as lit does");
_Static_assert(sizeof(litTexturedPremultiplied_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_litTexturedPremultiplied_vertexParams == UB_lit_vertexParams,
	"litTexturedPremultiplied must take vertexParams as lit does");
_Static_assert(sizeof(litTexturedPremultiplied_lightParams_t) == sizeof(lit_lightParams_t) && UB_litTexturedPremultiplied_lightParams == UB_lit_lightParams,
	"litTexturedPremultiplied must take lightParams as lit does");
_Static_assert(sizeof(litTexturedPremultiplied_materialParams_t) == sizeof(lit_materialParams_t) && UB_litTexturedPremultiplied_materialParams == UB_lit_materialParams,
	"litTexturedPremultiplied must take materialParams as lit does");
_Static_assert(ATTR_pixelArtLitTexturedPremultiplied_program_position == ATTR_litTextured_program_position && ATTR_pixelArtLitTexturedPremultiplied_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtLitTexturedPremultiplied_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtLitTexturedPremultiplied_program_color == ATTR_litTextured_program_color,
	"pixelArtLitTexturedPremultiplied must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtLitTexturedPremultiplied_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLitTexturedPremultiplied_modelParams == UB_lit_modelParams,
	"pixelArtLitTexturedPremultiplied must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedPremultiplied_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLitTexturedPremultiplied_vertexParams == UB_lit_vertexParams,
	"pixelArtLitTexturedPremultiplied must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedPremultiplied_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLitTexturedPremultiplied_lightParams == UB_lit_lightParams,
	"pixelArtLitTexturedPremultiplied must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedPremultiplied_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLitTexturedPremultiplied_materialParams == UB_lit_materialParams,
	"pixelArtLitTexturedPremultiplied must take materialParams as lit does");
_Static_assert(ATTR_unlitTexturedPremultiplied_program_position == ATTR_litTextured_program_position && ATTR_unlitTexturedPremultiplied_program_normal == ATTR_litTextured_program_normal && ATTR_unlitTexturedPremultiplied_program_uv == ATTR_litTextured_program_uv && ATTR_unlitTexturedPremultiplied_program_color == ATTR_litTextured_program_color,
	"unlitTexturedPremultiplied must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(unlitTexturedPremultiplied_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_unlitTexturedPremultiplied_vertexParams == UB_lit_vertexParams,
	"unlitTexturedPremultiplied must take vertexParams as lit does");
_Static_assert(sizeof(unlitTexturedPremultiplied_modelTransformParams_t) == sizeof(unlitTextured_modelTransformParams_t) && UB_unlitTexturedPremultiplied_modelTransformParams == UB_unlitTextured_modelTransformParams,
	"unlitTexturedPremultiplied must take modelTransformParams as unlitTextured does");
_Static_assert(sizeof(unlitTexturedPremultiplied_unlitMaterialParams_t) == sizeof(unlitTextured_unlitMaterialParams_t) && UB_unlitTexturedPremultiplied_unlitMaterialParams == UB_unlitTextured_unlitMaterialParams,
	"unlitTexturedPremultiplied must take unlitMaterialParams as unlitTextured does");
_Static_assert(ATTR_pixelArtUnlitTexturedPremultiplied_program_position == ATTR_litTextured_program_position && ATTR_pixelArtUnlitTexturedPremultiplied_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtUnlitTexturedPremultiplied_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtUnlitTexturedPremultiplied_program_color == ATTR_litTextured_program_color,
	"pixelArtUnlitTexturedPremultiplied must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtUnlitTexturedPremultiplied_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtUnlitTexturedPremultiplied_vertexParams == UB_lit_vertexParams,
	"pixelArtUnlitTexturedPremultiplied must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtUnlitTexturedPremultiplied_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtUnlitTexturedPremultiplied_modelParams == UB_lit_modelParams,
	"pixelArtUnlitTexturedPremultiplied must take modelParams as lit does");
_Static_assert(sizeof(pixelArtUnlitTexturedPremultiplied_unlitMaterialParams_t) == sizeof(unlitTextured_unlitMaterialParams_t) && UB_pixelArtUnlitTexturedPremultiplied_unlitMaterialParams == UB_unlitTextured_unlitMaterialParams,
	"pixelArtUnlitTexturedPremultiplied must take unlitMaterialParams as unlitTextured does");
_Static_assert(ATTR_litCutout_program_position == ATTR_lit_program_position && ATTR_litCutout_program_normal == ATTR_lit_program_normal && ATTR_litCutout_program_color == ATTR_lit_program_color,
	"litCutout must take the LIT layout as lit does");
_Static_assert(sizeof(litCutout_modelParams_t) == sizeof(lit_modelParams_t) && UB_litCutout_modelParams == UB_lit_modelParams,
	"litCutout must take modelParams as lit does");
_Static_assert(sizeof(litCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_litCutout_vertexParams == UB_lit_vertexParams,
	"litCutout must take vertexParams as lit does");
_Static_assert(sizeof(litCutout_lightParams_t) == sizeof(lit_lightParams_t) && UB_litCutout_lightParams == UB_lit_lightParams,
	"litCutout must take lightParams as lit does");
_Static_assert(sizeof(litCutout_materialParams_t) == sizeof(lit_materialParams_t) && UB_litCutout_materialParams == UB_lit_materialParams,
	"litCutout must take materialParams as lit does");
_Static_assert(ATTR_pixelArtLitCutout_program_position == ATTR_lit_program_position && ATTR_pixelArtLitCutout_program_normal == ATTR_lit_program_normal && ATTR_pixelArtLitCutout_program_color == ATTR_lit_program_color,
	"pixelArtLitCutout must take the LIT layout as lit does");
_Static_assert(sizeof(pixelArtLitCutout_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLitCutout_modelParams == UB_lit_modelParams,
	"pixelArtLitCutout must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLitCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLitCutout_vertexParams == UB_lit_vertexParams,
	"pixelArtLitCutout must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLitCutout_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLitCutout_lightParams == UB_lit_lightParams,
	"pixelArtLitCutout must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLitCutout_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLitCutout_materialParams == UB_lit_materialParams,
	"pixelArtLitCutout must take materialParams as lit does");
_Static_assert(ATTR_litTexturedCutout_program_position == ATTR_litTextured_program_position && ATTR_litTexturedCutout_program_normal == ATTR_litTextured_program_normal && ATTR_litTexturedCutout_program_uv == ATTR_litTextured_program_uv && ATTR_litTexturedCutout_program_color == ATTR_litTextured_program_color,
	"litTexturedCutout must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(litTexturedCutout_modelParams_t) == sizeof(lit_modelParams_t) && UB_litTexturedCutout_modelParams == UB_lit_modelParams,
	"litTexturedCutout must take modelParams as lit does");
_Static_assert(sizeof(litTexturedCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_litTexturedCutout_vertexParams == UB_lit_vertexParams,
	"litTexturedCutout must take vertexParams as lit does");
_Static_assert(sizeof(litTexturedCutout_lightParams_t) == sizeof(lit_lightParams_t) && UB_litTexturedCutout_lightParams == UB_lit_lightParams,
	"litTexturedCutout must take lightParams as lit does");
_Static_assert(sizeof(litTexturedCutout_materialParams_t) == sizeof(lit_materialParams_t) && UB_litTexturedCutout_materialParams == UB_lit_materialParams,
	"litTexturedCutout must take materialParams as lit does");
_Static_assert(ATTR_pixelArtLitTexturedCutout_program_position == ATTR_litTextured_program_position && ATTR_pixelArtLitTexturedCutout_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtLitTexturedCutout_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtLitTexturedCutout_program_color == ATTR_litTextured_program_color,
	"pixelArtLitTexturedCutout must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtLitTexturedCutout_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtLitTexturedCutout_modelParams == UB_lit_modelParams,
	"pixelArtLitTexturedCutout must take modelParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtLitTexturedCutout_vertexParams == UB_lit_vertexParams,
	"pixelArtLitTexturedCutout must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedCutout_lightParams_t) == sizeof(lit_lightParams_t) && UB_pixelArtLitTexturedCutout_lightParams == UB_lit_lightParams,
	"pixelArtLitTexturedCutout must take lightParams as lit does");
_Static_assert(sizeof(pixelArtLitTexturedCutout_materialParams_t) == sizeof(lit_materialParams_t) && UB_pixelArtLitTexturedCutout_materialParams == UB_lit_materialParams,
	"pixelArtLitTexturedCutout must take materialParams as lit does");
_Static_assert(ATTR_unlitTexturedCutout_program_position == ATTR_litTextured_program_position && ATTR_unlitTexturedCutout_program_normal == ATTR_litTextured_program_normal && ATTR_unlitTexturedCutout_program_uv == ATTR_litTextured_program_uv && ATTR_unlitTexturedCutout_program_color == ATTR_litTextured_program_color,
	"unlitTexturedCutout must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(unlitTexturedCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_unlitTexturedCutout_vertexParams == UB_lit_vertexParams,
	"unlitTexturedCutout must take vertexParams as lit does");
_Static_assert(sizeof(unlitTexturedCutout_modelTransformParams_t) == sizeof(unlitTextured_modelTransformParams_t) && UB_unlitTexturedCutout_modelTransformParams == UB_unlitTextured_modelTransformParams,
	"unlitTexturedCutout must take modelTransformParams as unlitTextured does");
_Static_assert(sizeof(unlitTexturedCutout_unlitMaterialParams_t) == sizeof(unlitTextured_unlitMaterialParams_t) && UB_unlitTexturedCutout_unlitMaterialParams == UB_unlitTextured_unlitMaterialParams,
	"unlitTexturedCutout must take unlitMaterialParams as unlitTextured does");
_Static_assert(ATTR_pixelArtUnlitTexturedCutout_program_position == ATTR_litTextured_program_position && ATTR_pixelArtUnlitTexturedCutout_program_normal == ATTR_litTextured_program_normal && ATTR_pixelArtUnlitTexturedCutout_program_uv == ATTR_litTextured_program_uv && ATTR_pixelArtUnlitTexturedCutout_program_color == ATTR_litTextured_program_color,
	"pixelArtUnlitTexturedCutout must take the LIT_TEXTURED layout as litTextured does");
_Static_assert(sizeof(pixelArtUnlitTexturedCutout_vertexParams_t) == sizeof(lit_vertexParams_t) && UB_pixelArtUnlitTexturedCutout_vertexParams == UB_lit_vertexParams,
	"pixelArtUnlitTexturedCutout must take vertexParams as lit does");
_Static_assert(sizeof(pixelArtUnlitTexturedCutout_modelParams_t) == sizeof(lit_modelParams_t) && UB_pixelArtUnlitTexturedCutout_modelParams == UB_lit_modelParams,
	"pixelArtUnlitTexturedCutout must take modelParams as lit does");
_Static_assert(sizeof(pixelArtUnlitTexturedCutout_unlitMaterialParams_t) == sizeof(unlitTextured_unlitMaterialParams_t) && UB_pixelArtUnlitTexturedCutout_unlitMaterialParams == UB_unlitTextured_unlitMaterialParams,
	"pixelArtUnlitTexturedCutout must take unlitMaterialParams as unlitTextured does");
