#!/bin/sh
# The void3d gate: everything a void3d commit has to survive, in one command.
#
#     sh scripts/gate3d.sh
#
# Stages, each printing one PASS / FAIL / SKIP line:
#
#   prepare   regenerate out/tmp/campfireScene.ms and the fourteen capture entries
#   tests     msc test out/tmp/test2d.ms
#   capture   build + run each capture entry, cmp every frame against its baseline
#   manifest  check the baselines against the committed SHA-256 list
#   android   build the arm64 .so
#
# The baselines are the SHA-256 hashes in `docs/baselines3d.sha256`, committed, so a clean
# checkout needs nothing the gate does not generate: the readback harness is
# tests/capture3d/, and the test and Android entries are written by `prepare`. A frame with no
# hash fails. GATE_ADOPT=1 records the hashes the manifest lacks, from this run: deliberate
# re-baselining only, in its own commit, with the reason written down. A hash is a D3D11 claim
# about this machine's driver; another GPU may render other bytes.
#
# Environment:
#   GATE_ADOPT=1           record the hashes docs/baselines3d.sha256 lacks, from this run
#   GATE_SKIP_CAPTURE=1    skip the capture stage (loudly)
#   GATE_SKIP_ANDROID=1    skip the android stage (loudly)
#   GATE_SKIP_BENCH=1      skip the bench stage (loudly)
#   GATE_DEVICE=1          build/run the GLES3 check against whatever adb sees
#   ANDROID_NDK=<path>     NDK root (default: the Windows SDK location)
set -u
cd "$(dirname "$0")/.."
export MSC_NO_GLOBAL_CACHE=1

FAILURES=0
SKIPPED=0
pass() { echo "PASS     $*"; }
fail() { echo "FAIL     $*"; FAILURES=$((FAILURES + 1)); }
skip() { echo "SKIP     $*"; SKIPPED=$((SKIPPED + 1)); }
note() { echo "         $*"; }

TMP=out/tmp
CAPTURE=$TMP/capture
WORK=$TMP/gate3d
SCENE=$TMP/campfireScene.ms
FRAMES="1 6 11 16"

mkdir -p "$WORK" "$CAPTURE/gate"

# Keeps the mtime stable when the content did not change, so msc can stay incremental.
replace_if_changed() {
	if [ -f "$2" ] && diff -q "$1" "$2" > /dev/null 2>&1; then rm -f "$1"; return 0; fi
	mv -f "$1" "$2"
}

# ---- prepare ------------------------------------------------------------------------------
#
# src/examples/campfireScene.ms does not compile on msc 0.2.53 (docs/VOID3D.md, Compiler
# notes): its imports are relative to src/examples, and Math.min/Math.max on two int32 return
# float64. The patched copy every entry builds against is derived here, so it cannot drift
# from the example. The transformation is checked by inverting it: the inverse sed has to
# reproduce the source byte for byte, which is what says nothing else was rewritten.
prepare_scene() {
	if [ ! -f src/examples/campfireScene.ms ]; then
		fail "prepare: src/examples/campfireScene.ms is missing"
		return 1
	fi
	sed -e 's|from "\.\./|from "../../src/|' \
		src/examples/campfireScene.ms > "$WORK/campfireScene.new"
	sed -e 's|from "\.\./\.\./src/|from "../|' \
		"$WORK/campfireScene.new" > "$WORK/campfireScene.back"
	if ! diff --strip-trailing-cr -q src/examples/campfireScene.ms "$WORK/campfireScene.back" > /dev/null; then
		fail "prepare: the patch of campfireScene.ms does not invert cleanly — re-derive it"
		diff --strip-trailing-cr src/examples/campfireScene.ms "$WORK/campfireScene.back" | head -20
		return 1
	fi
	changed=$(diff --strip-trailing-cr src/examples/campfireScene.ms "$WORK/campfireScene.new" | grep -c '^[<>]')
	replace_if_changed "$WORK/campfireScene.new" "$SCENE"
	rm -f "$WORK/campfireScene.back"
	note "prepare: $SCENE patched from the example, $changed lines changed (imports only)"
	return 0
}

# The six capture configurations. Generated rather than kept by hand: out/tmp is gitignored,
# so an entry that lives only there is one bad night away from being lost or silently edited.
#
# Every entry turns the camera snap off. The M2 and M3 baselines were taken before the camera
# had a snap (docs/VOID3D.md, M4 as built); at the campfire's target the snap happens to be a
# no-op, so the images are the same either way, and saying it keeps them that way on purpose.
write_entry() {
	name=$1
	extra=$2
	config=$3
	extraConfig=${4:-}
	outName=${5:-$1}
	{
		echo "// Generated by scripts/gate3d.sh. Edit the script, not this file."
		echo "import {"
		echo "	initCampfire,"
		echo "	frameCampfire,"
		echo "	configureCampfire,"
		echo "	configureCampfireCamera,"
		if [ -n "$extraConfig" ]; then
			echo "$extraConfig" | while IFS= read -r call; do echo "	${call%%(*},"; done
		fi
		echo "} from \"../campfireScene\";"
		echo "import { PixelArtSettings$extra } from \"../../../src/void3d/pixelArtRenderer\";"
		echo "@include(\"../../../src/sokol/bridge.h\");"
		echo "@include(\"capture.h\");"
		echo "@compile(\"./capture.c\");"
		echo "extern function voidRun(w: int32, h: int32, init: () => void, frame: () => void): void;"
		echo "extern function captureSwapchain(frame: int32): void;"
		echo "extern function captureQuit(): void;"
		echo ""
		echo "let frames: int32 = 0;"
		echo ""
		echo "function frame(): void {"
		echo "	frameCampfire();"
		echo "	if (frames == 1 || frames == 6 || frames == 11 || frames == 16) {"
		echo "		captureSwapchain(frames);"
		echo "	}"
		echo "	if (frames == 16) {"
		echo "		captureQuit();"
		echo "	}"
		echo "	frames = frames + 1;"
		echo "}"
		echo ""
		echo "$config"
		[ -n "$extraConfig" ] && echo "$extraConfig"
		echo "configureCampfireCamera(false, 0.0);"
		echo "voidRun(1280, 720, initCampfire, frame);"
	} > "$WORK/$outName.new"
	replace_if_changed "$WORK/$outName.new" "$CAPTURE/$outName.ms"
}

# Everything else the stages read from out/tmp: the readback harness (tracked in tests/capture3d),
# the test entry and the arm64 entry, whose imports are relative to out/tmp.
prepare_harness() {
	mkdir -p "$TMP/android"
	for file in capture.c capture.h; do
		cp "tests/capture3d/$file" "$WORK/$file.new"
		replace_if_changed "$WORK/$file.new" "$CAPTURE/$file"
	done
	echo 'import "../../src/test/index";' > "$WORK/test2d.new"
	replace_if_changed "$WORK/test2d.new" "$TMP/test2d.ms"
	sed -e 's|from "./campfireScene"|from "../campfireScene"|' \
		-e 's|@include("../sokol/|@include("../../../src/sokol/|' \
		src/examples/androidCampfireEntry.ms > "$WORK/androidEntry.new"
	replace_if_changed "$WORK/androidEntry.new" "$TMP/android/campfireEntry.ms"
}

prepare_entries() {
	write_entry campfireCapture "" \
		"configureCampfire(PixelArtSettings.full(), false);"
	write_entry campfirePaletteCapture "" \
		"configureCampfire(PixelArtSettings.full(), true);"
	write_entry campfirePreviewCapture "" \
		"configureCampfire(PixelArtSettings.preview(), true);"
	write_entry campfireDirectCapture "" \
		"configureCampfire({ ...PixelArtSettings.full(), postPass: false }, false);"
	write_entry campfireDepthCapture ", DepthSource" \
		"configureCampfire({ ...PixelArtSettings.full(), depthSource: DepthSource.DepthTexture }, false);"
	# The rebuild-after-context-loss path, against the plain palette-off baseline. Off Android
	# contextGeneration() never moves, so without this the re-upload branch of rebuildMeshes
	# would never execute anywhere: the entry marks every mesh stale at frame 3, and the frames
	# captured after it say whether the rebuilt buffers draw the same pixels.
	write_entry campfireRebuildCapture "" \
		"configureCampfire(PixelArtSettings.full(), false);" \
		"configureCampfireRebuildAt(3);"

	# The seventh configuration is for what the other six cannot reach. They all render a
	# scene placed once that never moves, so none of them exercises a node changing after
	# setup, or a child whose world matrix is its parent's times its own. This one turns the
	# log group every frame. Its baseline is new at M6, which is not the same thing as
	# re-baselining one of the six: those stay byte-identical and a change there is a defect.
	write_bench_entry
	write_pick_entry
	write_entry campfireSpinCapture "" "configureCampfire(PixelArtSettings.full(), false);" "configureCampfireLogSpin(0.11);"

	# Snow and embers on the particle path, the same run with every mesh rebuilt at frame 3, and a
	# palette swapped and a look greyed mid-run, then both put back. The seven above leave
	# particles and the look schedule off.
	write_entry campfireParticlesCapture "" "configureCampfire(PixelArtSettings.full(), false);" \
		"configureCampfireParticles(true);"
	write_entry campfireParticlesRebuildCapture "" \
		"configureCampfire(PixelArtSettings.full(), false);" \
		"configureCampfireParticles(true);
configureCampfireRebuildAt(3);"
	write_entry campfireLookCapture "" "configureCampfire(PixelArtSettings.full(), true);" \
		"configureCampfireLookSchedule(true);"
	# The ground greyed by its own lit material's saturation, with the post pass off and with the
	# palette on, and the same ground greyed in its vertex colours by colorSaturated, which must
	# draw the material's frames byte for byte.
	write_entry campfireGreyDirectCapture "" \
		"configureCampfire({ ...PixelArtSettings.full(), postPass: false }, false);" \
		"configureCampfireGreyGround($GREY_GROUND, false);"
	write_entry campfireGreyCpuCapture "" \
		"configureCampfire({ ...PixelArtSettings.full(), postPass: false }, false);" \
		"configureCampfireGreyGround($GREY_GROUND, true);"
	write_entry campfireGreyPaletteCapture "" "configureCampfire(PixelArtSettings.full(), true);" \
		"configureCampfireGreyGround($GREY_GROUND, false);"
	write_entry campfireForwardCapture "" "configureCampfire(PixelArtSettings.full(), false);" \
		"configureCampfireForward(true);
configureCampfireParticles(true);"
	note "prepare: fourteen capture entries written to $CAPTURE"
}

# msc build answers "Up to date" when only a header a compiled .c includes has changed, and the
# stale code is then linked into the binary with no diagnostic (docs/VOID3D.md, Compiler
# notes). gpu3d.c includes the two shader headers and gpu3d.h; the gate hashes them and evicts what
# was built from them in this checkout's build cache. The machine-wide cache is off for the run.
purge_stale_shader_objects() {
	stamp=$WORK/shaderStamp
	headers="src/void3d/shader3d.glsl.h src/void3d/pixelArt3d.glsl.h src/void3d/gpu3d.h"
	current=$(cat $headers 2>/dev/null | md5sum | cut -d' ' -f1)
	if [ ! -f src/void3d/shader3d.glsl.h ] || [ ! -f src/void3d/pixelArt3d.glsl.h ] ||
		[ ! -f src/void3d/gpu3d.h ]; then
		note "capture: a shader header or gpu3d.h is missing"
		return 0
	fi
	if [ -f "$stamp" ] && [ "$(cat "$stamp")" = "$current" ]; then
		return 0
	fi
	note "capture: a header gpu3d.c includes changed since the last gate — evicting the objects built from it"
	rm -f out/debug/.cache/*gpu3d* out/debug/.cache/*shader3d* out/debug/.cache/*pixelArt3d* 2>/dev/null
	echo "$current" > "$stamp"
}

# ---- entries ------------------------------------------------------------------------------

# msc 0.2.53 on Windows does not call main(): a module that only declares `function main()`
# builds into a binary that exits at once, and under --os=emcc it links the renderer out
# entirely. It has now been the same bug five times — mainSokol2d (fixed in ef1de70), and the
# four void3d entries mainSokol, mainCampfire, iosEntryAnim and iosEmbedEntry. A recurring bug
# class is infrastructure, not a fifth spot fix, so the sixth one fails here instead of
# shipping. Compiler card: 2026-09-20-main-not-called-windows.md.
run_entries() {
	missing=""
	checked=0
	for entry in src/examples/*.ms; do
		grep -qE '^(export )?function main\(' "$entry" || continue
		checked=$((checked + 1))
		grep -qE '^main\(\);' "$entry" || missing="$missing $(basename "$entry")"
	done
	if [ "$checked" -eq 0 ]; then
		skip "entries: no entry point declares main(), so there was nothing to check"
		return
	fi
	if [ -n "$missing" ]; then
		fail "entries: declared main() with no top-level call:$missing"
		echo "         each of those builds a binary that exits at once — add \`main();\` at the end"
		return
	fi
	broken=""
	for entry in src/examples/*.ms; do
		grep -qE '^(export )?function main\(' "$entry" || continue
		case "$(basename "$entry")" in
			ios*|android*) continue ;;
		esac
		msc build "$entry" > "$WORK/entry-build.log" 2>&1 || broken="$broken $(basename "$entry")"
	done
	if [ -n "$broken" ]; then
		fail "entries: declared main() and calls it, but does not build:$broken"
		tail -4 "$WORK/entry-build.log" | sed 's/^/         /'
		return
	fi
	pass "entries: $checked entry points declare main() and call it; the host ones build"
}

# ---- shaders ------------------------------------------------------------------------------
#
# REVIEWS-3D M6 defect 12: nothing checked that a .glsl.h was regenerated from its .glsl, and
# the M7 light block made the generated header load-bearing. shdc echoes the output path into
# the header twice (the Cmdline comment, the include-guard #error), so both lines are dropped
# and the comparison is then byte-exact.
run_shaders() {
	case "$(uname -s)-$(uname -m)" in
		Darwin-arm64)  SHDC="deps/sokol-tools-bin/bin/osx_arm64/sokol-shdc" ;;
		Darwin-*)      SHDC="deps/sokol-tools-bin/bin/osx/sokol-shdc" ;;
		Linux-aarch64) SHDC="deps/sokol-tools-bin/bin/linux_arm64/sokol-shdc" ;;
		Linux-*)       SHDC="deps/sokol-tools-bin/bin/linux/sokol-shdc" ;;
		*)             SHDC="deps/sokol-tools-bin/bin/win32/sokol-shdc.exe" ;;
	esac
	if [ ! -f "$SHDC" ]; then
		skip "shaders: sokol-shdc not found — .glsl.h freshness not checked"
		return
	fi
	SHDC_LANGS="metal_macos:glsl300es:wgsl:hlsl5"
	SHDC_LANGS_IOS="metal_macos:metal_ios:metal_sim:glsl300es:wgsl:hlsl5"
	for SHDC_SRC in src/sokol/shader.glsl src/void2d/shader2d.glsl src/void3d/shader3d.glsl \
		src/void3d/pixelArt3d.glsl; do
		SHDC_LANGS_PICK="$SHDC_LANGS"
		case "$SHDC_SRC" in
			src/sokol/*|src/void3d/*) SHDC_LANGS_PICK="$SHDC_LANGS_IOS" ;;
		esac
		SHDC_OUT="$WORK/fresh_$(basename "$SHDC_SRC" .glsl).h"
		if ! "$SHDC" -i "$SHDC_SRC" -o "$SHDC_OUT" -l "$SHDC_LANGS_PICK" -f sokol >/dev/null 2>&1; then
			fail "shaders: sokol-shdc failed on $SHDC_SRC"
			return
		fi
		sed -e '/^        sokol-shdc /d' -e '/Please include sokol_gfx.h before/d' "$SHDC_OUT" > "$SHDC_OUT.n"
		sed -e '/^        sokol-shdc /d' -e '/Please include sokol_gfx.h before/d' "$SHDC_SRC.h" > "$SHDC_SRC.h.n"
		if cmp -s "$SHDC_OUT.n" "$SHDC_SRC.h.n"; then
			pass "shaders: $SHDC_SRC.h is a fresh regeneration of its .glsl"
		else
			fail "shaders: $SHDC_SRC.h is stale — run scripts/regen-shaders.sh and commit it"
		fi
		rm -f "$SHDC_OUT" "$SHDC_OUT.n" "$SHDC_SRC.h.n"
	done
}

# The bench entry: warm up, measure, print machine-readable rows, quit. It reuses the capture
# harness's quit because that is what lets a windowed run end by itself.
write_bench_entry() {
	{
		echo "// Generated by scripts/gate3d.sh. Edit the script, not this file."
		echo "import {"
		echo "	initCampfire,"
		echo "	frameCampfire,"
		echo "	configureCampfire,"
		echo "	configureCampfireCamera,"
		echo "	configureCampfireLogSpin,"
		echo "	configureCampfireParticles,"
		echo "	campfireStats,"
		echo "	CampfireStats,"
		echo "} from \"../campfireScene\";"
		echo "import { PixelArtSettings } from \"../../../src/void3d/pixelArtRenderer\";"
		echo "@include(\"../../../src/sokol/bridge.h\");"
		echo "@include(\"capture.h\");"
		echo "@compile(\"./capture.c\");"
		echo "extern function voidRun(w: int32, h: int32, init: () => void, frame: () => void): void;"
		echo "extern function captureQuit(): void;"
		echo ""
		echo "const WARMUP: int32 = $BENCH_WARMUP;"
		echo "const MEASURED: int32 = $BENCH_FRAMES;"
		echo "let frames: int32 = 0;"
		echo "let started: float64 = 0.0;"
		echo "let cpu: float64 = 0.0;"
		echo "let base: CampfireStats = { drawItems: 0, nodes: 0, meshes: 0, rebuildable: 0, pipelines: 0, uniforms: 0, stack: 0 };"
		echo ""
		echo "function frame(): void {"
		echo "	const enter: float64 = performance.now();"
		echo "	frameCampfire();"
		echo "	const left: float64 = performance.now();"
		echo "	if (frames >= WARMUP) { cpu = cpu + (left - enter); }"
		echo "	frames = frames + 1;"
		echo "	if (frames == WARMUP) {"
		echo "		base = campfireStats();"
		echo "		started = performance.now();"
		echo "	}"
		echo "	if (frames == WARMUP + MEASURED) {"
		echo "		const elapsed: float64 = performance.now() - started;"
		echo "		const now: CampfireStats = campfireStats();"
		echo "		console.log(\`BENCH campfire.drawItems \${now.drawItems}\`);"
		echo "		console.log(\`BENCH campfire.nodes \${now.nodes}\`);"
		echo "		console.log(\`BENCH campfire.meshes \${now.meshes}\`);"
		echo "		console.log(\`BENCH campfire.rebuildable \${now.rebuildable}\`);"
		echo "		console.log(\`BENCH campfire.pipelines \${now.pipelines}\`);"
		echo "		console.log(\`BENCH growth.drawItems \${now.drawItems - base.drawItems}\`);"
		echo "		console.log(\`BENCH growth.nodes \${now.nodes - base.nodes}\`);"
		echo "		console.log(\`BENCH growth.meshes \${now.meshes - base.meshes}\`);"
		echo "		console.log(\`BENCH growth.pipelines \${now.pipelines - base.pipelines}\`);"
		echo "		console.log(\`BENCH growth.uniforms \${now.uniforms - base.uniforms}\`);"
		echo "		console.log(\`BENCH growth.stack \${now.stack - base.stack}\`);"
		echo "		console.log(\`BENCH time.cpuMsPerFrame \${cpu / (MEASURED as float64)}\`);"
		echo "		console.log(\`BENCH time.wallMsPerFrame \${elapsed / (MEASURED as float64)}\`);"
		echo "		captureQuit();"
		echo "	}"
		echo "}"
		echo ""
		echo "configureCampfire(PixelArtSettings.full(), false);"
		echo "configureCampfireCamera(false, 0.0);"
		echo "configureCampfireLogSpin(0.11);"
		echo "configureCampfireParticles(true);"
		echo "voidRun(1280, 720, initCampfire, frame);"
	} > "$WORK/campfireBench.new"
	replace_if_changed "$WORK/campfireBench.new" "$CAPTURE/campfireBench.ms"
}

# Taps through the view and blit the renderer drew with: a snapping, panning camera with a
# margin, so the blit carries a remainder, and the logs turning. Each tap is aimed with
# `project` through that same pair, so a mapping error both share passes; nothing reads pixels.
write_pick_entry() {
	{
		echo "// Generated by scripts/gate3d.sh. Edit the script, not this file."
		echo "import {"
		echo "	initCampfire,"
		echo "	frameCampfire,"
		echo "	configureCampfire,"
		echo "	configureCampfireCamera,"
		echo "	configureCampfireLogSpin,"
		echo "	campfireTargets,"
		echo "	campfirePixelOf,"
		echo "	campfireTap,"
		echo "	CampfireTargets,"
		echo "} from \"../campfireScene\";"
		echo "import { PixelArtSettings } from \"../../../src/void3d/pixelArtRenderer\";"
		echo "import { NodeId, SceneError } from \"../../../src/void3d/scene\";"
		echo "import { PickHit, PickError } from \"../../../src/void3d/pick\";"
		echo "import { Vec3 } from \"../../../src/math/math3d\";"
		echo "@include(\"../../../src/sokol/bridge.h\");"
		echo "@include(\"capture.h\");"
		echo "@compile(\"./capture.c\");"
		echo "extern function voidRun(w: int32, h: int32, init: () => void, frame: () => void): void;"
		echo "extern function captureQuit(): void;"
		echo ""
		echo "let frames: int32 = 0;"
		echo ""
		echo "function tap(label: string, on: NodeId, owner: NodeId, expectHit: boolean): void {"
		echo "	const aimed: Result<Vec3, SceneError> = campfirePixelOf(on);"
		echo "	if (!aimed.ok) {"
		echo "		console.log(\`PICK \${label} FAIL the target is not a live mesh node\`);"
		echo "		return;"
		echo "	}"
		echo "	const at: Vec3 = aimed.value;"
		echo "	const x: float32 = Math.floor(at.x) + 0.5;"
		echo "	const y: float32 = Math.floor(at.y) + 0.5;"
		echo "	const picked: Result<PickHit, PickError> = campfireTap(x, y);"
		echo "	if (!picked.ok) {"
		echo "		const verdict: string = expectHit ? \"FAIL\" : \"PASS\";"
		echo "		console.log(\`PICK \${label} \${verdict} pixel=(\${x}, \${y}) nothing hit\`);"
		echo "		return;"
		echo "	}"
		echo "	const hit: PickHit = picked.value;"
		echo "	const right: boolean = expectHit && hit.owner.index == owner.index &&"
		echo "		hit.owner.generation == owner.generation;"
		echo "	const verdict: string = right ? \"PASS\" : \"FAIL\";"
		echo "	const where: string = \`pixel=(\${x}, \${y}) owner=\${hit.owner.index}\`;"
		echo "	const what: string = \`mesh=\${hit.mesh.index} distance=\${hit.distance}\`;"
		echo "	console.log(\`PICK \${label} \${verdict} \${where} \${what}\`);"
		echo "}"
		echo ""
		echo "function frame(): void {"
		echo "	frameCampfire();"
		echo "	frames = frames + 1;"
		echo "	if (frames == $PICK_FRAME) {"
		echo "		const targets: CampfireTargets = campfireTargets();"
		echo "		tap(\"logs\", targets.firstLog, targets.logs, true);"
		echo "		tap(\"bakedStone\", targets.bakedStone, targets.bakedStone, true);"
		echo "		tap(\"plainStone\", targets.plainStone, targets.plainStone, false);"
		echo "		captureQuit();"
		echo "	}"
		echo "}"
		echo ""
		echo "configureCampfire({ ...PixelArtSettings.full(), margin: 1 }, false);"
		echo "configureCampfireCamera(true, 0.3);"
		echo "configureCampfireLogSpin(0.11);"
		echo "voidRun(1280, 720, initCampfire, frame);"
	} > "$WORK/campfirePick.new"
	replace_if_changed "$WORK/campfirePick.new" "$CAPTURE/campfirePick.ms"
}

# ---- pick ---------------------------------------------------------------------------------

run_pick() {
	if [ ! -f "$CAPTURE/capture.c" ] || [ ! -f "$CAPTURE/capture.h" ]; then
		skip "pick: $CAPTURE/capture.c and capture.h are missing (gitignored out/tmp harness)"
		return
	fi
	if ! msc build "$CAPTURE/campfirePick.ms" > "$WORK/pick-build.log" 2>&1; then
		fail "pick: the pick entry did not build"
		tail -5 "$WORK/pick-build.log" | sed 's/^/         /'
		return
	fi
	if ! "./out/debug/campfirePick.exe" > "$WORK/pick.log" 2>&1; then
		fail "pick: the pick run did not finish"
		tail -5 "$WORK/pick.log" | sed 's/^/         /'
		return
	fi
	rows=$(grep -c '^PICK ' "$WORK/pick.log" || true)
	wrong=$(grep -c '^PICK [a-zA-Z]* FAIL' "$WORK/pick.log" || true)
	if [ "$rows" -ne 3 ] || [ "$wrong" -ne 0 ]; then
		fail "pick: $wrong of $rows tap(s) on the campfire picked the wrong thing (3 expected)"
		grep '^PICK ' "$WORK/pick.log" | sed 's/^/         /'
		return
	fi
	pass "pick: 3 taps aimed through the campfire's drawn view, snapping and panning, picked right"
	grep '^PICK ' "$WORK/pick.log" | sed 's/^PICK /         pick: /'
}

# ---- bench --------------------------------------------------------------------------------

# Counters gate hard and milliseconds only report. The counters here are the lengths of every
# piece of frame state, and a growth of anything but zero means a steady frame allocated —
# which "Frame state is preallocated... nothing in `frame` allocates" says it must not.
#
# There is deliberately no millisecond threshold. A wall-clock gate needs the run-to-run
# variance measured first, and a threshold tighter than that variance is a false alarm every
# other run, which ends with the gate being switched off. The number is printed so it can be
# watched; docs/VOID3D.md records the variance when it has been taken over enough runs.
run_bench() {
	if [ "${GATE_SKIP_BENCH:-0}" = "1" ]; then
		skip "bench: GATE_SKIP_BENCH=1 — frame-state growth was not measured"
		return
	fi
	if [ ! -f "$CAPTURE/campfireBench.ms" ]; then
		skip "bench: $CAPTURE/campfireBench.ms is missing"
		return
	fi
	if ! msc build "$CAPTURE/campfireBench.ms" --release > "$WORK/bench-build.log" 2>&1; then
		fail "bench: the bench entry did not build"
		tail -5 "$WORK/bench-build.log" | sed 's/^/         /'
		return
	fi
	if ! "./out/release/campfireBench.exe" > "$WORK/bench.log" 2>&1; then
		fail "bench: the bench run did not finish"
		tail -5 "$WORK/bench.log" | sed 's/^/         /'
		return
	fi
	rows=$(grep -c '^BENCH ' "$WORK/bench.log" || true)
	if [ "$rows" -eq 0 ]; then
		fail "bench: the run produced no BENCH rows"
		return
	fi
	grew=""
	for row in $(grep '^BENCH growth\.' "$WORK/bench.log" | awk '{print $2 "=" $3}'); do
		case "$row" in
			*=0) ;;
			*) grew="$grew $row" ;;
		esac
	done
	if [ -n "$grew" ]; then
		fail "bench: frame state grew during a steady run — the frame allocated:$grew"
		return
	fi
	cpu=$(grep '^BENCH time.cpuMsPerFrame' "$WORK/bench.log" | awk '{print $3}')
	wall=$(grep '^BENCH time.wallMsPerFrame' "$WORK/bench.log" | awk '{print $3}')
	counts=$(grep '^BENCH campfire\.' "$WORK/bench.log" | awk '{printf "%s=%s ", substr($2,10), $3}')
	pass "bench: no frame-state growth over $BENCH_FRAMES frames; $counts"
	note "bench: ${cpu} ms of CPU per frame; wall clock ${wall} ms is vsync-bound, not a cost"
	note "bench: reported only — docs/VOID3D.md records the variance behind any future threshold"
}

# ---- device -------------------------------------------------------------------------------

# The GLES3 backend is the one Hibernal ships on and the one with no byte-level numbers. It ran
# for the first time before M7 (tests/device/gles3Campfire.png) — on the Android emulator, which
# is not a device. This stage is a loud SKIP by default rather than a silent omission: a green
# gate should say out loud that the shipping backend is unverified here, the way the baseline
# skips do. GATE_DEVICE=1 builds, installs and runs it against whatever adb can see.
run_device() {
	if [ "${GATE_DEVICE:-0}" != "1" ]; then
		skip "device: GATE_DEVICE=1 not set — no GLES3 run this gate; every pixel claim here is D3D11 only"
		return
	fi
	adb=${ADB:-$HOME/AppData/Local/Android/Sdk/platform-tools/adb.exe}
	if [ ! -x "$adb" ] && ! command -v adb > /dev/null 2>&1; then
		skip "device: no adb (set ADB)"
		return
	fi
	[ -x "$adb" ] || adb=adb
	target=$("$adb" devices | awk 'NR>1 && $2=="device" { print $1; exit }')
	if [ -z "$target" ]; then
		skip "device: adb sees no device"
		return
	fi
	kind=$("$adb" -s "$target" shell getprop ro.build.characteristics | tr -d '
')
	egl=$("$adb" -s "$target" shell getprop ro.hardware.egl | tr -d '
')
	if ! "$adb" -s "$target" shell pidof com.metascript.voidsample > /dev/null 2>&1; then
		skip "device: $target ($kind, egl=$egl) is there but the app is not running — see tests/device/README.md"
		return
	fi
	"$adb" -s "$target" exec-out screencap -p > "$WORK/device.png" 2>/dev/null
	colours=$(magick "$WORK/device.png" -format "%k" info: 2>/dev/null || echo 0)
	# A palette quantizes a real frame to a couple of dozen colours, so the count alone cannot
	# tell it from a blank one; a blank frame is one colour over nearly every pixel.
	dominant=$(magick "$WORK/device.png" -format %c histogram:info: 2>/dev/null |
		awk '{ n = $1 + 0; t += n; if (n > m) m = n } END { if (t) printf "%d", 100 * m / t; else print 100 }')
	if [ "$colours" -lt 8 ] || [ "$dominant" -gt 90 ]; then
		fail "device: $target rendered $colours colours, one of them over $dominant% of the frame — blank or near-blank"
		return
	fi
	pass "device: $target ($kind, egl=$egl) rendering, $colours colours, largest $dominant% — NOT a baseline comparison"
}

# ---- oracle -------------------------------------------------------------------------------

# Heaps is the reference for everything this port copies, and until scripts/oracle.sh existed
# every claim about what Heaps does rested on somebody having read the file. This runs the
# port's side of tests/oracle/*.cases against a snapshot taken from real Heaps and committed,
# so an ordinary gate needs no Haxe. `sh scripts/oracle.sh regen <cases>` retakes the snapshot
# and is the only part that does. Every file in that directory is checked, so adding a case
# file needs no edit here — which is how it was written when only bounds3d existed, and
# scene3d would then have been added and silently never run.
run_oracle() {
	found=0
	agreed=0
	diverged=0
	for cases in tests/oracle/*.cases; do
		[ -f "$cases" ] || continue
		found=$((found + 1))
		snapshot=${cases%.cases}.snapshot
		if [ ! -f "$snapshot" ]; then
			skip "oracle: no snapshot for $cases — run 'sh scripts/oracle.sh regen $cases' with Haxe"
			return
		fi
		if sh scripts/oracle.sh check "$cases" > "$WORK/oracle.log" 2>&1; then
			agreed=$((agreed + $(grep -c '^AGREES' "$WORK/oracle.log")))
			diverged=$((diverged + $(grep -c '^DIVERGES' "$WORK/oracle.log")))
		else
			fail "oracle: $cases and real Heaps disagree in a way nothing declared"
			grep -E '^(MISMATCH|GRADUATED|MISSING)' "$WORK/oracle.log" | head -8 | sed 's/^/         /'
			return
		fi
	done
	if [ "$found" = 0 ]; then
		skip "oracle: no tests/oracle/*.cases to check"
		return
	fi
	pass "oracle: $agreed case(s) agree with real Heaps and $diverged diverge as declared, over $found file(s)"
}

# ---- style --------------------------------------------------------------------------------

# CODE-STYLE section 16 caps a line at 100 columns with a tab counted as 4. The M5 review found
# five over-long lines and the M6 review found thirteen more, in the files M5 had just fixed. A
# finding that recurs the next milestone is infrastructure, not a third review comment.
#
# Scoped to what this port owns: src/void3d, its tests, and the campfire. void2d has its own
# gate and its own backlog.
STYLE_PATHS="src/void3d src/test/scene3dCheck.ms src/test/boundsCheck.ms src/test/meshDataCheck.ms src/test/drawCheck.ms src/test/billboardCheck.ms"

run_style() {
	long=$(
		for path in $STYLE_PATHS; do
			find "$path" -name '*.ms' 2>/dev/null
		done | while read -r file; do
			expand -t 4 "$file" | awk -v f="$file" 'length($0) > 100 { print f ":" FNR " (" length($0) " cols)" }'
		done
	)
	if [ -n "$long" ]; then
		count=$(echo "$long" | grep -c .)
		fail "style: $count line(s) over 100 columns (CODE-STYLE section 16)"
		echo "$long" | head -8 | sed 's/^/         /'
		return
	fi
	pass "style: no line over 100 columns in $(echo $STYLE_PATHS | wc -w) path(s)"
}

# ---- allocation ---------------------------------------------------------------------------

# "Frame state is preallocated... nothing in `frame` allocates" (docs/VOID3D.md, Data types) is
# the one claim in this port that the bench stage cannot see: the bench gates the *lengths* of
# the frame state, and an allocation that does not change a length is invisible to it. That is
# exactly how M6 shipped a per-node `msArrayCopy` in `refresh` with a green gate — the copy trap
# of CODE-STYLE section 5, `const xs: Vec<T> = someStruct.field`, which copies and frees on
# every visit without moving any length.
#
# The M6 review found it by reading the emitted C, so that is what this checks. It is
# deterministic and it can fail, which is the whole point: a gate that cannot fail is worse than
# no gate. Read C emitted from the bench entry into fixed names, never the object cache by
# mtime, which can hold another entry's or a reverted build. A `Vec` of structs with owned
# fields copies through `<T>ArrayCopy`, not `msArrayCopy`.
FRAME_PATH_FUNCTIONS="scene:syncWorld scene:collectDrawList scene:refresh scene:collectLights
	scene:setLocal scene:setMeshOf animation:update animation:keys animation:blendTo
	animation:syncPose animation:syncMeshFrame particles:updateEmitter particles:spawn
	particles:stepParticle particles:colorAt particles:moveParticle particles:particleValue
	particles:emitterValue particles:writeInstances draw:writeStream"

RENDER_PATH_FUNCTIONS="renderer:beginFrame renderer:blockFits renderer:drawPassLists renderer:drawScreen
	renderer:endFrame pass76ist:collect pass76ist:sortBackToFront pass76ist:drawPassList
	draw:drawItem draw:bindItem draw:writeUniforms draw:applyBlock pipeline67ache:pipelineFor
	pipeline67ache:pipelineKey pixel65rt82enderer:renderFrame pixel65rt82enderer:resizeTargets
	pixel65rt82enderer:bindScreenTextures pixel65rt82enderer:writePostParams
	pixel65rt82enderer:viewFor pixel65rt82enderer:drawScene pixel65rt82enderer:drawPost
	pixel65rt82enderer:drawBlit pixel65rt82enderer:rampsHaveLevels pixel65rt82enderer:levelsAt
	pixel65rt82enderer:billboardLevels
	program77ap:drawnFor forward82enderer:renderFrame forward82enderer:resizeTargets
	camera:resolve camera:writeCameraBlock blit:writeBlitParams blit:lowResView palette:upload
	target:beginPass"

# Module names as msc spells them in emitted file names: an upper-case letter becomes its code.
PICK_PATH_FUNCTIONS="pick:pickNearest pick:pickableOwner pick:meshHit bounds:rayIntersection
	mesh68ata:rayIntersection mesh68ata:cornerOf ray:transformed"

# $1 entry, $2 label, $3 the module:function list. Prints nothing and returns 0 when clean;
# otherwise records the failure and returns 1.
check_array_copies() {
	rm -f out/debug/*ZsrcZvoid3dZ*Oms.c
	if ! msc build "$1" --emit=c > "$WORK/allocation.log" 2>&1; then
		fail "allocation: emitting C for $1 failed; see $WORK/allocation.log"
		return 1
	fi
	offenders=""
	for entry in $3; do
		module=${entry%%:*}
		fn=${entry#*:}
		emitted=$(ls out/debug/*ZsrcZvoid3dZ${module}Oms.c 2>/dev/null | head -1)
		if [ -z "$emitted" ] || ! grep -q "^[a-zA-Z_].*[^a-zA-Z0-9_]${fn}__M.*{[[:space:]]*$" "$emitted"; then
			fail "allocation: the emitted C of $module.ms has no body for $fn — renamed or unreachable?"
			return 1
		fi
		copies=$(awk "/^[a-zA-Z_].*\y${fn}__M.*\{[ \t]*\$/,/^}/" "$emitted" |
			grep -c 'ArrayCopy(' || true)
		[ "$copies" -gt 0 ] && offenders="$offenders ${fn}=${copies}"
	done
	if [ -n "$offenders" ]; then
		fail "allocation: the $2 copies an array — ArrayCopy in:$offenders"
		echo "         CODE-STYLE section 5, the copy trap: index the field or take a Span view"
		return 1
	fi
	return 0
}

run_allocation() {
	if [ ! -f "$CAPTURE/campfireBench.ms" ] || [ ! -f "$CAPTURE/campfirePick.ms" ]; then
		skip "allocation: $CAPTURE/campfireBench.ms or campfirePick.ms is missing"
		return
	fi
	check_array_copies "$CAPTURE/campfireBench.ms" "frame path" \
		"$FRAME_PATH_FUNCTIONS $RENDER_PATH_FUNCTIONS" || return
	check_array_copies "$CAPTURE/campfirePick.ms" "pick path" "$PICK_PATH_FUNCTIONS" || return
	pass "allocation: no array copy in the frame path ($(echo $FRAME_PATH_FUNCTIONS))"
	note "allocation: nor in the render path ($(echo $RENDER_PATH_FUNCTIONS))"
	note "allocation: nor in the pick path ($(echo $PICK_PATH_FUNCTIONS))"
}

# ---- pending ------------------------------------------------------------------------------

# tests/PENDING3D.md on rexa's rule: a listed case that stops holding fails the run, and its row
# is deleted in the same commit as the fix. Enforced in both directions, because a list with a
# forcing function in only one direction rots from the other end.
#
# What this stage sees is that a **sentinel is present**, not that the **divergence still
# holds** — measured: fixing `size()` while leaving its `// PENDING3D:` line in place passes
# here and fails `oracle`. Only the rows with a `diverges=` oracle case are enforced
# behaviourally; tests/PENDING3D.md names them. The `*)` branch
# below is deliberately a requirement and not a skip: a row naming a sentinel nobody wrote
# fails rather than passing quietly.
run_pending() {
	if [ ! -f "$PENDING" ]; then
		skip "pending: $PENDING is missing, so nothing holds the known divergences to account"
		return
	fi
	rows=$(grep -oE '^\| `[a-z0-9-]+`' "$PENDING" | tr -d '|` ' | sort)
	tags=$(grep -rhoE 'PENDING3D: [a-z0-9-]+' src/ | sed 's/PENDING3D: //' | sort -u)
	graduated=""
	for row in $rows; do
		case "$row" in
			baselines-adopted-circular)
				grep -q 'plausible\* M4 images' docs/VOID3D.md || graduated="$graduated $row" ;;
			gles3-emulator-only)
				grep -q 'not a device' docs/VOID3D.md || graduated="$graduated $row" ;;
			*)
				echo "$tags" | grep -qx "$row" || graduated="$graduated $row" ;;
		esac
	done
	unlisted=""
	for tag in $tags; do
		echo "$rows" | grep -qx "$tag" || unlisted="$unlisted $tag"
	done
	if [ -n "$graduated" ]; then
		fail "pending: listed but no longer holding — delete the row in the commit that fixed it:$graduated"
		return
	fi
	if [ -n "$unlisted" ]; then
		fail "pending: marked in the tree with no row in $PENDING:$unlisted"
		return
	fi
	count=$(echo "$rows" | grep -c .)
	pass "pending: $count rows in $PENDING, every sentinel present and every sentinel listed"
}

# ---- tests --------------------------------------------------------------------------------

run_tests() {
	if [ ! -f "$TMP/test2d.ms" ]; then
		skip "tests: $TMP/test2d.ms is missing (one line: import \"../../src/test/index\")"
		return
	fi
	if msc test "$TMP/test2d.ms" > "$WORK/tests.log" 2>&1; then
		summary=$(grep -E '^ *Tests ' "$WORK/tests.log" | tail -1 | tr -s ' ')
		if [ -z "$summary" ]; then
			fail "tests: no summary line; msc test exits 0 when the test binary crashes"
			grep -nE 'terminated|Assertion|×' "$WORK/tests.log" | head -10
		elif grep -qE 'failed' "$WORK/tests.log"; then
			fail "tests:$summary"
			grep -nE 'failed|FAIL' "$WORK/tests.log" | head -20
		else
			pass "tests:$summary"
		fi
	else
		fail "tests: msc test exited nonzero"
		tail -30 "$WORK/tests.log"
	fi
}

run_gltf_cpu() {
	printf '%s\n' \
		'import { loadGltf } from "../../../src/void3d/gltf";' \
		'const loaded = loadGltf("{\"asset\":{\"version\":\"2.0\"},\"scenes\":[{\"nodes\":[]}],\"nodes\":[],\"meshes\":[],\"accessors\":[],\"bufferViews\":[],\"buffers\":[]}", []);' \
		'console.log(loaded.ok);' \
		> "$WORK/gltfCpu.ms"
	rm -f out/debug/gltfCpu.exe
	if ! msc build "$WORK/gltfCpu.ms" > "$WORK/gltfCpu.build.log" 2>&1; then
		fail "gltf-cpu: the decoder does not build without sokol"
		tail -20 "$WORK/gltfCpu.build.log"
		return
	fi
	if [ "$(./out/debug/gltfCpu.exe 2>&1 | tr -d '\r\n')" != "true" ]; then
		fail "gltf-cpu: the CPU-only smoke did not decode an empty glTF scene"
		return
	fi
	pass "gltf-cpu: decoder builds and runs without the sokol GPU bridge"
}

# ---- capture ------------------------------------------------------------------------------
#
# One configuration: rebuild the entry, run it, and hash all four frames against the baseline
# it claims to reproduce. The committed docs/baselines3d.sha256 *is* the baseline set, so a
# clean checkout has everything the comparison needs, and a frame with no hash there fails.
# The binary is deleted first so the link is always redone; the object eviction above is what
# makes a stale shader impossible.
#
# A frame that matches is also kept as out/tmp/capture/<baseline>_<frame>.ppm. That copy is
# only ever read to measure a later difference (AE, PAE); it decides nothing.
expected_hash() {
	tr -d '\r' < "$MANIFEST" | sed -n "s|^\([0-9a-f]\{64\}\) \*$1\$|\1|p" | head -1
}

baseline_names() {
	for prefix in before m3palette m3preview m3direct m3depth m6spin m11particles m11look \
		m12greydirect m12greypalette m14forward; do
		for frame in $FRAMES; do
			echo "${prefix}_$frame.ppm"
		done
	done
}

# GATE_ADOPT=1 only: writes the hash of a baseline the manifest does not have yet, keeping the
# manifest in baseline_names order.
record_hash() {
	tr -d '\r' < "$MANIFEST" | grep -v " \*$1\$" > "$WORK/manifest.old"
	echo "$2 *$1" >> "$WORK/manifest.old"
	: > "$WORK/manifest.new"
	for key in $(baseline_names); do
		grep " \*$key\$" "$WORK/manifest.old" >> "$WORK/manifest.new" || true
	done
	cp "$WORK/manifest.new" "$MANIFEST"
}

run_capture() {
	name=$1
	baseline=$2
	what=$3
	entry=$CAPTURE/$name.ms
	if [ ! -f "$entry" ]; then
		fail "capture $name: the entry is missing"
		return
	fi
	rm -f "out/debug/$name.exe" "$CAPTURE/gate/${name}_"*.ppm
	if ! msc build "$entry" > "$WORK/$name.build.log" 2>&1; then
		fail "capture $name: build failed"
		tail -30 "$WORK/$name.build.log"
		return
	fi
	if [ ! -f "out/debug/$name.exe" ]; then
		fail "capture $name: out/debug/$name.exe was not produced"
		return
	fi
	if ! CAPTURE_PREFIX="$CAPTURE/gate/$name" "./out/debug/$name.exe" > "$WORK/$name.run.log" 2>&1; then
		rm -f "$CAPTURE/gate/${name}_"*.ppm
		fail "capture $name: the run exited nonzero"
		tail -20 "$WORK/$name.run.log"
		return
	fi
	missing=0
	differing=0
	adopted=0
	for frame in $FRAMES; do
		got=$CAPTURE/gate/${name}_$frame.ppm
		key=${baseline}_$frame.ppm
		want=$CAPTURE/$key
		if [ ! -f "$got" ]; then
			fail "capture $name: frame $frame was not captured"
			return
		fi
		hash=$(sha256sum "$got" | cut -d' ' -f1)
		expected=$(expected_hash "$key")
		if [ -z "$expected" ]; then
			if [ "${GATE_ADOPT:-0}" = "1" ]; then
				record_hash "$key" "$hash"
				cp "$got" "$want"
				adopted=$((adopted + 1))
			else
				missing=$((missing + 1))
			fi
			continue
		fi
		if [ "$hash" = "$expected" ]; then
			cmp -s "$got" "$want" 2>/dev/null || cp "$got" "$want"
			continue
		fi
		differing=$((differing + 1))
		note "capture $name: frame $frame does not hash to $key in $MANIFEST"
		if [ -f "$want" ] && [ "$(sha256sum "$want" | cut -d' ' -f1)" = "$expected" ] &&
			command -v magick > /dev/null 2>&1; then
			absolute=$(magick compare -metric AE "$want" "$got" null: 2>&1 | tail -1)
			peak=$(magick compare -metric PAE "$want" "$got" null: 2>&1 | tail -1)
			note "capture $name: frame $frame AE $absolute, PAE $peak"
		else
			note "capture $name: no local image of $key to measure the difference against"
		fi
	done
	if [ "$differing" -gt 0 ]; then
		fail "capture $name ($what): $differing of 4 frames differ from ${baseline}_*.ppm"
	elif [ "$missing" -gt 0 ]; then
		fail "capture $name ($what): $missing of 4 frames have no ${baseline}_* hash in $MANIFEST (GATE_ADOPT=1 records them)"
	elif [ "$adopted" -gt 0 ]; then
		skip "capture $name ($what): recorded $adopted new ${baseline}_* hashes in $MANIFEST — commit them, and write down why"
	else
		pass "capture $name ($what): 4 frames byte-identical to ${baseline}_*.ppm"
	fi
}

# The look schedule swaps the palette and greys the look, then puts both back before frame 16,
# and frame 1 is before any of it: both have to be the palette-on image, byte for byte. A swap
# that left the LUT or the post block anywhere but where it was fails here.
run_look_restored() {
	for frame in 1 16; do
		got=$CAPTURE/gate/campfireLookCapture_$frame.ppm
		expected=$(expected_hash "m3palette_$frame.ppm")
		if [ ! -f "$got" ] || [ -z "$expected" ]; then
			fail "capture look: frame $frame was not captured or m3palette_$frame.ppm has no hash"
			return
		fi
		if [ "$(sha256sum "$got" | cut -d' ' -f1)" != "$expected" ]; then
			fail "capture look: frame $frame is not the palette-on image after the swap and back"
			return
		fi
	done
	pass "capture look: frames 1 and 16 byte-identical to m3palette_*.ppm around the swap"
}

count_off_ratio() {
	magick "$1" -channel R -evaluate multiply "$3" -channel G -evaluate multiply "$4" \
		-channel B -evaluate multiply "$5" +channel "$WORK/ratioPredicted.ppm"
	magick "$1" "$2" -compose difference -composite -separate -evaluate-sequence max \
		-threshold 0 "$WORK/ratioGround.png"
	magick "$WORK/ratioPredicted.ppm" "$2" -compose difference -composite -separate \
		-evaluate-sequence max -threshold 0.6% "$WORK/ratioGround.png" -compose multiply \
		-composite -format "%[fx:round(mean*w*h)] " info:
	magick "$WORK/ratioGround.png" -format "%[fx:round(mean*w*h)] " info:
	magick "$WORK/ratioPredicted.ppm" "$1" -separate -evaluate-sequence max -threshold 99.9% 		"$WORK/ratioGround.png" -compose multiply -composite -format "%[fx:round(mean*w*h)]" info:
}

run_light_multiplies() {
	ground=$(sed -n 's/^const GROUND: Rgba = { red: \([0-9.]*\), green: \([0-9.]*\), blue: \([0-9.]*\),.*/\1 \2 \3/p' \
		src/examples/campfireScene.ms)
	luma=$(sed -n 's/^const LUMA_[A-Z]*: float32 = \([0-9.]*\);/\1/p' src/math/math3d.ms | tr '\n' ' ')
	if [ "$(echo $ground | wc -w)" -ne 3 ] || [ "$(echo $luma | wc -w)" -ne 3 ]; then
		fail "multiply: GROUND in campfireScene.ms or LUMA_* in math3d.ms not found (got '$ground' / '$luma')"
		return
	fi
	ratios=$(echo "$ground $luma $GREY_GROUND" | awk '{
		l = $1 * $4 + $2 * $5 + $3 * $6
		for (i = 1; i <= 3; i++) printf "%.9f ", ($i * (1 + $7) - l * $7) / $i
	}')
	for frame in $FRAMES; do
		plain=$CAPTURE/gate/campfireDirectCapture_$frame.ppm
		greyed=$CAPTURE/gate/campfireGreyDirectCapture_$frame.ppm
		if [ ! -f "$plain" ] || [ ! -f "$greyed" ]; then
			fail "multiply: frame $frame of campfireDirectCapture or campfireGreyDirectCapture was not captured"
			return
		fi
		set -- $(count_off_ratio "$plain" "$greyed" $ratios)
		if [ "$2" -eq 0 ]; then
			fail "multiply: frame $frame has no ground pixel that greying changed"
			return
		fi
		if [ "$3" -ne 0 ]; then
			fail "multiply: frame $frame, $3 ground pixels reach 255 in the plain frame or plain × grey/ground; the ratio cannot hold where a channel clips"
			return
		fi
		if [ "$1" -ne 0 ]; then
			fail "multiply: frame $frame, $1 of $2 ground pixels are not the plain ground × grey/ground"
			return
		fi
	done
	pass "multiply: the greyed ground is the plain ground × grey/ground ($ratios) in 4 frames"
}

run_captures() {
	if [ "${GATE_SKIP_CAPTURE:-0}" = "1" ]; then
		skip "capture: GATE_SKIP_CAPTURE=1 — the fourteen configurations were not built, not run, not compared"
		return
	fi
	purge_stale_shader_objects
	run_capture campfireCapture        before     "palette off"
	run_capture campfirePaletteCapture m3palette  "palette on"
	run_capture campfirePreviewCapture m3preview  "preview"
	run_capture campfireDirectCapture  m3direct   "postPass off"
	run_capture campfireDepthCapture   m3depth    "DepthTexture"
	run_capture campfireRebuildCapture before     "rebuilt mid-run"
	run_capture campfireSpinCapture    m6spin     "log group turning"
	run_capture campfireParticlesCapture m11particles "snow and embers"
	run_capture campfireParticlesRebuildCapture m11particles "particles, rebuilt mid-run"
	run_capture campfireLookCapture    m11look    "palette swapped, greyed, restored"
	run_look_restored
	run_capture campfireGreyDirectCapture  m12greydirect  "ground greyed by its material, postPass off"
	run_light_multiplies
	run_capture campfireGreyCpuCapture     m12greydirect  "ground greyed in its vertex colours"
	run_capture campfireGreyPaletteCapture m12greypalette "ground greyed by its material, palette on"
	run_capture campfireForwardCapture     m14forward     "forward preset, core programs, particles"
}

# ---- manifest -----------------------------------------------------------------------------

MANIFEST=docs/baselines3d.sha256
PENDING=tests/PENDING3D.md
BENCH_WARMUP=${GATE_BENCH_WARMUP:-30}
BENCH_FRAMES=${GATE_BENCH_FRAMES:-300}
PICK_FRAME=12
GREY_GROUND=-0.75

# The manifest holds one hash per baseline and nothing else: a baseline without a hash is a
# frame nothing checks, and a hash without a baseline is a claim nothing makes.
run_manifest() {
	if [ ! -f "$MANIFEST" ]; then
		fail "manifest: $MANIFEST is missing, so no frame can be compared"
		return
	fi
	tr -d '\r' < "$MANIFEST" | sed 's|^[0-9a-f]\{64\} \*||' > "$WORK/manifest.names"
	baseline_names > "$WORK/manifest.expected"
	malformed=$(tr -d '\r' < "$MANIFEST" | grep -vc '^[0-9a-f]\{64\} \*[a-z0-9]*_[0-9]*\.ppm$' || true)
	if [ "$malformed" -gt 0 ] || ! diff -q "$WORK/manifest.expected" "$WORK/manifest.names" > /dev/null; then
		fail "manifest: $MANIFEST is not exactly one hash per baseline, in order"
		diff "$WORK/manifest.expected" "$WORK/manifest.names" | head -12
		return
	fi
	pass "manifest: $(wc -l < "$WORK/manifest.expected" | tr -d ' ') hashes, one per baseline"
}

# ---- android ------------------------------------------------------------------------------

run_android() {
	if [ "${GATE_SKIP_ANDROID:-0}" = "1" ]; then
		skip "android: GATE_SKIP_ANDROID=1 — the arm64 .so was not built"
		return
	fi
	entry=$TMP/android/campfireEntry.ms
	if [ ! -f "$entry" ]; then
		skip "android: $entry is missing"
		return
	fi
	ndk=${ANDROID_NDK:-$HOME/AppData/Local/Android/Sdk/ndk/28.0.13004108}
	cc=$ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
	if [ ! -f "$cc" ]; then
		skip "android: no NDK clang at $cc (set ANDROID_NDK)"
		return
	fi
	if msc build "$entry" --os=android --app=lib \
		--cc="$cc --target=aarch64-linux-android26" \
		--output="$TMP/android/libVoidAndroid.so" > "$WORK/android.log" 2>&1; then
		pass "android: arm64 libVoidAndroid.so built, $(wc -c < "$TMP/android/libVoidAndroid.so") bytes"
	else
		fail "android: the arm64 build failed"
		tail -30 "$WORK/android.log"
	fi
}

# ---- run ----------------------------------------------------------------------------------

echo "void3d gate"
echo "  msc      $(msc --version 2>&1 | sed 's/\x1b\[[0-9;]*m//g' | tr -d '\r\n')"
echo "  commit   $(git rev-parse --short HEAD 2>/dev/null) on $(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
echo

if prepare_scene; then
	prepare_harness
	prepare_entries
	pass "prepare: campfireScene.ms and the fourteen capture entries are current"
else
	fail "prepare: the capture entries were not written"
fi
run_entries
run_shaders
run_pending
run_tests
run_gltf_cpu
run_captures
run_manifest
run_allocation
run_oracle
run_style
run_device
run_pick
run_bench
run_android

echo
if [ "$FAILURES" -gt 0 ]; then
	echo "GATE FAILED — $FAILURES failing stage(s), $SKIPPED skipped"
	exit 1
fi
if [ "$SKIPPED" -gt 0 ]; then
	echo "GATE GREEN with $SKIPPED skipped stage(s) — read the SKIP lines before trusting this"
	exit 0
fi
echo "GATE GREEN"
