#!/bin/sh
# The void3d gate: everything a void3d commit has to survive, in one command.
#
#     sh scripts/gate3d.sh
#
# Stages, each printing one PASS / FAIL / SKIP line:
#
#   prepare   regenerate out/tmp/campfireScene.ms and the five capture entries
#   tests     msc test out/tmp/test2d.ms
#   capture   build + run each capture entry, cmp every frame against its baseline
#   android   build the arm64 .so
#
# Everything the capture stage reads and writes lives under out/tmp, which is gitignored: the
# baselines are evidence, not source. A missing baseline is a loud SKIP, never a pass.
# GATE_ADOPT=1 writes the missing ones from this run — deliberate re-baselining only, and it
# says what it adopted so the milestone can write down which image it replaced.
#
# Environment:
#   GATE_ADOPT=1           adopt missing baselines from this run
#   GATE_SKIP_CAPTURE=1    skip the capture stage (loudly)
#   GATE_SKIP_ANDROID=1    skip the android stage (loudly)
#   ANDROID_NDK=<path>     NDK root (default: the Windows SDK location)
set -u
cd "$(dirname "$0")/.."

FAILURES=0
SKIPPED=0
pass() { echo "PASS     $*"; }
fail() { echo "FAIL     $*"; FAILURES=$((FAILURES + 1)); }
skip() { echo "SKIP     $*"; SKIPPED=$((SKIPPED + 1)); }
note() { echo "         $*"; }

TMP=out/tmp
CAPTURE=$TMP/capture
WORK=$TMP/gate3d
SCENE=$TMP/campfireScene.ms
FRAMES="1 6 11 16"

mkdir -p "$WORK" "$CAPTURE/gate"

# Keeps the mtime stable when the content did not change, so msc can stay incremental.
replace_if_changed() {
	if [ -f "$2" ] && diff -q "$1" "$2" > /dev/null 2>&1; then rm -f "$1"; return 0; fi
	mv -f "$1" "$2"
}

# ---- prepare ------------------------------------------------------------------------------
#
# src/examples/campfireScene.ms does not compile on msc 0.2.53 (docs/VOID3D.md, Compiler
# notes): its imports are relative to src/examples, and Math.min/Math.max on two int32 return
# float64. The patched copy every entry builds against is derived here, so it cannot drift
# from the example. The transformation is checked by inverting it: the inverse sed has to
# reproduce the source byte for byte, which is what says nothing else was rewritten.
prepare_scene() {
	if [ ! -f src/examples/campfireScene.ms ]; then
		fail "prepare: src/examples/campfireScene.ms is missing"
		return 1
	fi
	sed -e 's|from "\.\./|from "../../src/|' \
		-e 's|const clamped: int32 = Math.max(0, Math.min(TUFT_CELL - 1, offset));|const clamped: int32 = (Math.max(0, Math.min(TUFT_CELL - 1, offset)) as int32);|' \
		src/examples/campfireScene.ms > "$WORK/campfireScene.new"
	sed -e 's|from "\.\./\.\./src/|from "../|' \
		-e 's|const clamped: int32 = (Math.max(0, Math.min(TUFT_CELL - 1, offset)) as int32);|const clamped: int32 = Math.max(0, Math.min(TUFT_CELL - 1, offset));|' \
		"$WORK/campfireScene.new" > "$WORK/campfireScene.back"
	if ! diff --strip-trailing-cr -q src/examples/campfireScene.ms "$WORK/campfireScene.back" > /dev/null; then
		fail "prepare: the patch of campfireScene.ms does not invert cleanly — re-derive it"
		diff --strip-trailing-cr src/examples/campfireScene.ms "$WORK/campfireScene.back" | head -20
		return 1
	fi
	changed=$(diff --strip-trailing-cr src/examples/campfireScene.ms "$WORK/campfireScene.new" | grep -c '^[<>]')
	replace_if_changed "$WORK/campfireScene.new" "$SCENE"
	rm -f "$WORK/campfireScene.back"
	note "prepare: $SCENE patched from the example, $changed lines changed (imports, one as int32)"
	return 0
}

# The five capture configurations. Generated rather than kept by hand: out/tmp is gitignored,
# so an entry that lives only there is one bad night away from being lost or silently edited.
#
# Every entry turns the camera snap off. The M2 and M3 baselines were taken before the camera
# had a snap (docs/VOID3D.md, M4 as built); at the campfire's target the snap happens to be a
# no-op, so the images are the same either way, and saying it keeps them that way on purpose.
write_entry() {
	name=$1
	extra=$2
	config=$3
	{
		echo "// Generated by scripts/gate3d.sh. Edit the script, not this file."
		echo "import {"
		echo "	initCampfire,"
		echo "	frameCampfire,"
		echo "	configureCampfire,"
		echo "	configureCampfireCamera,"
		echo "} from \"../campfireScene\";"
		echo "import { PixelArtSettings$extra } from \"../../../src/void3d/pixelArtRenderer\";"
		echo "@include(\"../../../src/sokol/bridge.h\");"
		echo "@include(\"capture.h\");"
		echo "@compile(\"./capture.c\");"
		echo "extern function voidRun(w: int32, h: int32, init: () => void, frame: () => void): void;"
		echo "extern function captureSwapchain(frame: int32): void;"
		echo "extern function captureQuit(): void;"
		echo ""
		echo "let frames: int32 = 0;"
		echo ""
		echo "function frame(): void {"
		echo "	frameCampfire();"
		echo "	if (frames == 1 || frames == 6 || frames == 11 || frames == 16) {"
		echo "		captureSwapchain(frames);"
		echo "	}"
		echo "	if (frames == 16) {"
		echo "		captureQuit();"
		echo "	}"
		echo "	frames = frames + 1;"
		echo "}"
		echo ""
		echo "$config"
		echo "configureCampfireCamera(false, 0.0);"
		echo "voidRun(1280, 720, initCampfire, frame);"
	} > "$WORK/$name.new"
	replace_if_changed "$WORK/$name.new" "$CAPTURE/$name.ms"
}

prepare_entries() {
	write_entry campfireCapture "" \
		"configureCampfire(PixelArtSettings.full(), false);"
	write_entry campfirePaletteCapture "" \
		"configureCampfire(PixelArtSettings.full(), true);"
	write_entry campfirePreviewCapture "" \
		"configureCampfire(PixelArtSettings.preview(), true);"
	write_entry campfireDirectCapture "" \
		"configureCampfire({ ...PixelArtSettings.full(), postPass: false }, false);"
	write_entry campfireDepthCapture ", DepthSource" \
		"configureCampfire({ ...PixelArtSettings.full(), depthSource: DepthSource.DepthTexture }, false);"
	note "prepare: five capture entries written to $CAPTURE"
}

# msc build answers "Up to date" when only a header a compiled .c includes has changed, and
# the stale shader is then linked into the binary with no diagnostic (docs/VOID3D.md, Compiler
# notes). The gate notices the header itself and evicts what includes it: this checkout's
# build cache, and the global object keyed on gpu3d.c.
purge_stale_shader_objects() {
	stamp=$WORK/shaderStamp
	current=$(md5sum src/void3d/shader3d.glsl.h 2>/dev/null | cut -d' ' -f1)
	if [ -z "$current" ]; then
		note "capture: src/void3d/shader3d.glsl.h is missing"
		return 0
	fi
	if [ -f "$stamp" ] && [ "$(cat "$stamp")" = "$current" ]; then
		return 0
	fi
	note "capture: shader3d.glsl.h changed since the last gate — evicting the objects that include it"
	rm -f out/debug/.cache/*gpu3d* out/debug/.cache/*shader3d* 2>/dev/null
	for object in "$HOME"/.metascript/cache/objects/*.o; do
		[ -f "$object" ] || continue
		if grep -l gpu3d "$object" > /dev/null 2>&1; then
			note "capture: evicting $(basename "$object")"
			rm -f "$object"
		fi
	done
	echo "$current" > "$stamp"
}

# ---- tests --------------------------------------------------------------------------------

run_tests() {
	if [ ! -f "$TMP/test2d.ms" ]; then
		skip "tests: $TMP/test2d.ms is missing (one line: import \"../../src/test/index\")"
		return
	fi
	if msc test "$TMP/test2d.ms" > "$WORK/tests.log" 2>&1; then
		summary=$(grep -E '^ *Tests ' "$WORK/tests.log" | tail -1 | tr -s ' ')
		if grep -qE 'failed' "$WORK/tests.log"; then
			fail "tests:$summary"
			grep -nE 'failed|FAIL' "$WORK/tests.log" | head -20
		else
			pass "tests:$summary"
		fi
	else
		fail "tests: msc test exited nonzero"
		tail -30 "$WORK/tests.log"
	fi
}

# ---- capture ------------------------------------------------------------------------------
#
# One configuration: rebuild the entry, run it, and cmp all four frames against the baseline it
# claims to reproduce. The binary is deleted first so the link is always redone; the object
# eviction above is what makes a stale shader impossible.
run_capture() {
	name=$1
	baseline=$2
	what=$3
	entry=$CAPTURE/$name.ms
	if [ ! -f "$entry" ]; then
		fail "capture $name: the entry is missing"
		return
	fi
	rm -f "out/debug/$name.exe"
	if ! msc build "$entry" > "$WORK/$name.build.log" 2>&1; then
		fail "capture $name: build failed"
		tail -30 "$WORK/$name.build.log"
		return
	fi
	if [ ! -f "out/debug/$name.exe" ]; then
		fail "capture $name: out/debug/$name.exe was not produced"
		return
	fi
	rm -f "$CAPTURE/gate/${name}_"*.ppm
	if ! CAPTURE_PREFIX="$CAPTURE/gate/$name" "./out/debug/$name.exe" > "$WORK/$name.run.log" 2>&1; then
		fail "capture $name: the run exited nonzero"
		tail -20 "$WORK/$name.run.log"
		return
	fi
	missing=0
	differing=0
	adopted=0
	for frame in $FRAMES; do
		got=$CAPTURE/gate/${name}_$frame.ppm
		want=$CAPTURE/${baseline}_$frame.ppm
		if [ ! -f "$got" ]; then
			fail "capture $name: frame $frame was not captured"
			return
		fi
		if [ ! -f "$want" ]; then
			if [ "${GATE_ADOPT:-0}" = "1" ]; then
				cp "$got" "$want"
				adopted=$((adopted + 1))
			else
				missing=$((missing + 1))
			fi
			continue
		fi
		if ! cmp -s "$got" "$want"; then
			differing=$((differing + 1))
			note "capture $name: frame $frame differs from $want"
			if command -v magick > /dev/null 2>&1; then
				absolute=$(magick compare -metric AE "$want" "$got" null: 2>&1 | tail -1)
				peak=$(magick compare -metric PAE "$want" "$got" null: 2>&1 | tail -1)
				note "capture $name: frame $frame AE $absolute, PAE $peak"
			fi
		fi
	done
	if [ "$differing" -gt 0 ]; then
		fail "capture $name ($what): $differing of 4 frames differ from ${baseline}_*.ppm"
	elif [ "$missing" -gt 0 ]; then
		skip "capture $name ($what): $missing of 4 baselines ${baseline}_*.ppm missing — built and rendered, compared nothing (GATE_ADOPT=1 adopts)"
	elif [ "$adopted" -gt 0 ]; then
		skip "capture $name ($what): adopted $adopted of 4 baselines as ${baseline}_*.ppm from this run — write down what was replaced and why"
	else
		pass "capture $name ($what): 4 frames byte-identical to ${baseline}_*.ppm"
	fi
}

run_captures() {
	if [ "${GATE_SKIP_CAPTURE:-0}" = "1" ]; then
		skip "capture: GATE_SKIP_CAPTURE=1 — the five configurations were not built, not run, not compared"
		return
	fi
	if [ ! -f "$CAPTURE/capture.c" ] || [ ! -f "$CAPTURE/capture.h" ]; then
		skip "capture: $CAPTURE/capture.c and capture.h are missing (the D3D11 readback harness lives in gitignored out/tmp)"
		return
	fi
	purge_stale_shader_objects
	run_capture campfireCapture        before     "palette off"
	run_capture campfirePaletteCapture m3palette  "palette on"
	run_capture campfirePreviewCapture m3preview  "preview"
	run_capture campfireDirectCapture  m3direct   "postPass off"
	run_capture campfireDepthCapture   m3depth    "DepthTexture"
}

# ---- android ------------------------------------------------------------------------------

run_android() {
	if [ "${GATE_SKIP_ANDROID:-0}" = "1" ]; then
		skip "android: GATE_SKIP_ANDROID=1 — the arm64 .so was not built"
		return
	fi
	entry=$TMP/android/campfireEntry.ms
	if [ ! -f "$entry" ]; then
		skip "android: $entry is missing"
		return
	fi
	ndk=${ANDROID_NDK:-$HOME/AppData/Local/Android/Sdk/ndk/28.0.13004108}
	cc=$ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
	if [ ! -f "$cc" ]; then
		skip "android: no NDK clang at $cc (set ANDROID_NDK)"
		return
	fi
	if msc build "$entry" --os=android --app=lib \
		--cc="$cc --target=aarch64-linux-android26" \
		--output="$TMP/android/libVoidAndroid.so" > "$WORK/android.log" 2>&1; then
		pass "android: arm64 libVoidAndroid.so built, $(wc -c < "$TMP/android/libVoidAndroid.so") bytes"
	else
		fail "android: the arm64 build failed"
		tail -30 "$WORK/android.log"
	fi
}

# ---- run ----------------------------------------------------------------------------------

echo "void3d gate"
echo "  msc      $(msc --version 2>&1 | sed 's/\x1b\[[0-9;]*m//g' | tr -d '\r\n')"
echo "  commit   $(git rev-parse --short HEAD 2>/dev/null) on $(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
echo

if prepare_scene; then
	prepare_entries
	pass "prepare: campfireScene.ms and the five capture entries are current"
else
	fail "prepare: the capture entries were not written"
fi
run_tests
run_captures
run_android

echo
if [ "$FAILURES" -gt 0 ]; then
	echo "GATE FAILED — $FAILURES failing stage(s), $SKIPPED skipped"
	exit 1
fi
if [ "$SKIPPED" -gt 0 ]; then
	echo "GATE GREEN with $SKIPPED skipped stage(s) — read the SKIP lines before trusting this"
	exit 0
fi
echo "GATE GREEN"
