#!/bin/sh
# The void3d gate: everything a void3d commit has to survive, in one command.
#
#     sh scripts/gate3d.sh
#
# Stages, each printing one PASS / FAIL / SKIP line:
#
#   prepare   regenerate out/tmp/campfireScene.ms and the seven capture entries
#   tests     msc test out/tmp/test2d.ms
#   capture   build + run each capture entry, cmp every frame against its baseline
#   manifest  check the baselines against the committed SHA-256 list
#   android   build the arm64 .so
#
# Everything the capture stage reads and writes lives under out/tmp, which is gitignored: the
# baselines are evidence, not source. A missing baseline is a loud SKIP, never a pass.
# GATE_ADOPT=1 writes the missing ones from this run — deliberate re-baselining only, and it
# says what it adopted so the milestone can write down which image it replaced.
#
# The baselines themselves are gitignored, so `docs/baselines3d.sha256` is committed beside the
# code: it is what lets someone six months from now tell whether the images they hold are the
# images a byte-identity claim was made against. GATE_WRITE_MANIFEST=1 rewrites it, which is a
# deliberate act that belongs in the same commit as the re-baselining it records.
#
# Environment:
#   GATE_ADOPT=1           adopt missing baselines from this run
#   GATE_WRITE_MANIFEST=1  rewrite docs/baselines3d.sha256 from the baselines on disk
#   GATE_SKIP_CAPTURE=1    skip the capture stage (loudly)
#   GATE_SKIP_ANDROID=1    skip the android stage (loudly)
#   GATE_SKIP_BENCH=1      skip the bench stage (loudly)
#   GATE_DEVICE=1          build/run the GLES3 check against whatever adb sees
#   ANDROID_NDK=<path>     NDK root (default: the Windows SDK location)
set -u
cd "$(dirname "$0")/.."

FAILURES=0
SKIPPED=0
pass() { echo "PASS     $*"; }
fail() { echo "FAIL     $*"; FAILURES=$((FAILURES + 1)); }
skip() { echo "SKIP     $*"; SKIPPED=$((SKIPPED + 1)); }
note() { echo "         $*"; }

TMP=out/tmp
CAPTURE=$TMP/capture
WORK=$TMP/gate3d
SCENE=$TMP/campfireScene.ms
FRAMES="1 6 11 16"

mkdir -p "$WORK" "$CAPTURE/gate"

# Keeps the mtime stable when the content did not change, so msc can stay incremental.
replace_if_changed() {
	if [ -f "$2" ] && diff -q "$1" "$2" > /dev/null 2>&1; then rm -f "$1"; return 0; fi
	mv -f "$1" "$2"
}

# ---- prepare ------------------------------------------------------------------------------
#
# src/examples/campfireScene.ms does not compile on msc 0.2.53 (docs/VOID3D.md, Compiler
# notes): its imports are relative to src/examples, and Math.min/Math.max on two int32 return
# float64. The patched copy every entry builds against is derived here, so it cannot drift
# from the example. The transformation is checked by inverting it: the inverse sed has to
# reproduce the source byte for byte, which is what says nothing else was rewritten.
prepare_scene() {
	if [ ! -f src/examples/campfireScene.ms ]; then
		fail "prepare: src/examples/campfireScene.ms is missing"
		return 1
	fi
	sed -e 's|from "\.\./|from "../../src/|' \
		src/examples/campfireScene.ms > "$WORK/campfireScene.new"
	sed -e 's|from "\.\./\.\./src/|from "../|' \
		"$WORK/campfireScene.new" > "$WORK/campfireScene.back"
	if ! diff --strip-trailing-cr -q src/examples/campfireScene.ms "$WORK/campfireScene.back" > /dev/null; then
		fail "prepare: the patch of campfireScene.ms does not invert cleanly — re-derive it"
		diff --strip-trailing-cr src/examples/campfireScene.ms "$WORK/campfireScene.back" | head -20
		return 1
	fi
	changed=$(diff --strip-trailing-cr src/examples/campfireScene.ms "$WORK/campfireScene.new" | grep -c '^[<>]')
	replace_if_changed "$WORK/campfireScene.new" "$SCENE"
	rm -f "$WORK/campfireScene.back"
	note "prepare: $SCENE patched from the example, $changed lines changed (imports only)"
	return 0
}

# The six capture configurations. Generated rather than kept by hand: out/tmp is gitignored,
# so an entry that lives only there is one bad night away from being lost or silently edited.
#
# Every entry turns the camera snap off. The M2 and M3 baselines were taken before the camera
# had a snap (docs/VOID3D.md, M4 as built); at the campfire's target the snap happens to be a
# no-op, so the images are the same either way, and saying it keeps them that way on purpose.
write_entry() {
	name=$1
	extra=$2
	config=$3
	extraConfig=${4:-}
	outName=${5:-$1}
	{
		echo "// Generated by scripts/gate3d.sh. Edit the script, not this file."
		echo "import {"
		echo "	initCampfire,"
		echo "	frameCampfire,"
		echo "	configureCampfire,"
		echo "	configureCampfireCamera,"
		[ -n "$extraConfig" ] && echo "	${extraConfig%%(*},"
		echo "} from \"../campfireScene\";"
		echo "import { PixelArtSettings$extra } from \"../../../src/void3d/pixelArtRenderer\";"
		echo "@include(\"../../../src/sokol/bridge.h\");"
		echo "@include(\"capture.h\");"
		echo "@compile(\"./capture.c\");"
		echo "extern function voidRun(w: int32, h: int32, init: () => void, frame: () => void): void;"
		echo "extern function captureSwapchain(frame: int32): void;"
		echo "extern function captureQuit(): void;"
		echo ""
		echo "let frames: int32 = 0;"
		echo ""
		echo "function frame(): void {"
		echo "	frameCampfire();"
		echo "	if (frames == 1 || frames == 6 || frames == 11 || frames == 16) {"
		echo "		captureSwapchain(frames);"
		echo "	}"
		echo "	if (frames == 16) {"
		echo "		captureQuit();"
		echo "	}"
		echo "	frames = frames + 1;"
		echo "}"
		echo ""
		echo "$config"
		[ -n "$extraConfig" ] && echo "$extraConfig"
		echo "configureCampfireCamera(false, 0.0);"
		echo "voidRun(1280, 720, initCampfire, frame);"
	} > "$WORK/$outName.new"
	replace_if_changed "$WORK/$outName.new" "$CAPTURE/$outName.ms"
}

prepare_entries() {
	write_entry campfireCapture "" \
		"configureCampfire(PixelArtSettings.full(), false);"
	write_entry campfirePaletteCapture "" \
		"configureCampfire(PixelArtSettings.full(), true);"
	write_entry campfirePreviewCapture "" \
		"configureCampfire(PixelArtSettings.preview(), true);"
	write_entry campfireDirectCapture "" \
		"configureCampfire({ ...PixelArtSettings.full(), postPass: false }, false);"
	write_entry campfireDepthCapture ", DepthSource" \
		"configureCampfire({ ...PixelArtSettings.full(), depthSource: DepthSource.DepthTexture }, false);"
	# The rebuild-after-context-loss path, against the plain palette-off baseline. Off Android
	# contextGeneration() never moves, so without this the re-upload branch of rebuildMeshes
	# would never execute anywhere: the entry marks every mesh stale at frame 3, and the frames
	# captured after it say whether the rebuilt buffers draw the same pixels.
	write_entry campfireRebuildCapture "" \
		"configureCampfire(PixelArtSettings.full(), false);" \
		"configureCampfireRebuildAt(3);"

	# The seventh configuration is for what the other six cannot reach. They all render a
	# scene placed once that never moves, so none of them exercises a node changing after
	# setup, or a child whose world matrix is its parent's times its own. This one turns the
	# log group every frame. Its baseline is new at M6, which is not the same thing as
	# re-baselining one of the six: those stay byte-identical and a change there is a defect.
	write_bench_entry
	write_entry campfireSpinCapture "" "configureCampfire(PixelArtSettings.full(), false);" "configureCampfireLogSpin(0.11);"
	note "prepare: seven capture entries written to $CAPTURE"
}

# msc build answers "Up to date" when only a header a compiled .c includes has changed, and the
# stale code is then linked into the binary with no diagnostic (docs/VOID3D.md, Compiler
# notes). gpu3d.c includes shader3d.glsl.h and gpu3d.h; the gate hashes both and evicts what
# was built from them: this checkout's build cache, and the global object keyed on gpu3d.c.
purge_stale_shader_objects() {
	stamp=$WORK/shaderStamp
	current=$(cat src/void3d/shader3d.glsl.h src/void3d/gpu3d.h 2>/dev/null | md5sum | cut -d' ' -f1)
	if [ ! -f src/void3d/shader3d.glsl.h ] || [ ! -f src/void3d/gpu3d.h ]; then
		note "capture: src/void3d/shader3d.glsl.h or gpu3d.h is missing"
		return 0
	fi
	if [ -f "$stamp" ] && [ "$(cat "$stamp")" = "$current" ]; then
		return 0
	fi
	note "capture: a header gpu3d.c includes changed since the last gate — evicting the objects built from it"
	rm -f out/debug/.cache/*gpu3d* out/debug/.cache/*shader3d* 2>/dev/null
	for object in "$HOME"/.metascript/cache/objects/*.o; do
		[ -f "$object" ] || continue
		if grep -l gpu3d "$object" > /dev/null 2>&1; then
			note "capture: evicting $(basename "$object")"
			rm -f "$object"
		fi
	done
	echo "$current" > "$stamp"
}

# ---- entries ------------------------------------------------------------------------------

# msc 0.2.53 on Windows does not call main(): a module that only declares `function main()`
# builds into a binary that exits at once, and under --os=emcc it links the renderer out
# entirely. It has now been the same bug five times — mainSokol2d (fixed in ef1de70), and the
# four void3d entries mainSokol, mainCampfire, iosEntryAnim and iosEmbedEntry. A recurring bug
# class is infrastructure, not a fifth spot fix, so the sixth one fails here instead of
# shipping. Compiler card: 2026-09-20-main-not-called-windows.md.
run_entries() {
	missing=""
	checked=0
	for entry in src/examples/*.ms; do
		grep -qE '^(export )?function main\(' "$entry" || continue
		checked=$((checked + 1))
		grep -qE '^main\(\);' "$entry" || missing="$missing $(basename "$entry")"
	done
	if [ "$checked" -eq 0 ]; then
		skip "entries: no entry point declares main(), so there was nothing to check"
		return
	fi
	if [ -n "$missing" ]; then
		fail "entries: declared main() with no top-level call:$missing"
		echo "         each of those builds a binary that exits at once — add \`main();\` at the end"
		return
	fi
	broken=""
	for entry in src/examples/*.ms; do
		grep -qE '^(export )?function main\(' "$entry" || continue
		case "$(basename "$entry")" in
			ios*|android*) continue ;;
		esac
		msc build "$entry" > "$WORK/entry-build.log" 2>&1 || broken="$broken $(basename "$entry")"
	done
	if [ -n "$broken" ]; then
		fail "entries: declared main() and calls it, but does not build:$broken"
		tail -4 "$WORK/entry-build.log" | sed 's/^/         /'
		return
	fi
	pass "entries: $checked entry points declare main() and call it; the host ones build"
}

# The bench entry: warm up, measure, print machine-readable rows, quit. It reuses the capture
# harness's quit because that is what lets a windowed run end by itself.
write_bench_entry() {
	{
		echo "// Generated by scripts/gate3d.sh. Edit the script, not this file."
		echo "import {"
		echo "	initCampfire,"
		echo "	frameCampfire,"
		echo "	configureCampfire,"
		echo "	configureCampfireCamera,"
		echo "	campfireStats,"
		echo "	CampfireStats,"
		echo "} from \"../campfireScene\";"
		echo "import { PixelArtSettings } from \"../../../src/void3d/pixelArtRenderer\";"
		echo "@include(\"../../../src/sokol/bridge.h\");"
		echo "@include(\"capture.h\");"
		echo "@compile(\"./capture.c\");"
		echo "extern function voidRun(w: int32, h: int32, init: () => void, frame: () => void): void;"
		echo "extern function captureQuit(): void;"
		echo ""
		echo "const WARMUP: int32 = $BENCH_WARMUP;"
		echo "const MEASURED: int32 = $BENCH_FRAMES;"
		echo "let frames: int32 = 0;"
		echo "let started: float64 = 0.0;"
		echo "let cpu: float64 = 0.0;"
		echo "let base: CampfireStats = { drawItems: 0, nodes: 0, meshes: 0, rebuildable: 0, pipelines: 0, uniforms: 0, stack: 0 };"
		echo ""
		echo "function frame(): void {"
		echo "	const enter: float64 = performance.now();"
		echo "	frameCampfire();"
		echo "	const left: float64 = performance.now();"
		echo "	if (frames >= WARMUP) { cpu = cpu + (left - enter); }"
		echo "	frames = frames + 1;"
		echo "	if (frames == WARMUP) {"
		echo "		base = campfireStats();"
		echo "		started = performance.now();"
		echo "	}"
		echo "	if (frames == WARMUP + MEASURED) {"
		echo "		const elapsed: float64 = performance.now() - started;"
		echo "		const now: CampfireStats = campfireStats();"
		echo "		console.log(\`BENCH campfire.drawItems \${now.drawItems}\`);"
		echo "		console.log(\`BENCH campfire.nodes \${now.nodes}\`);"
		echo "		console.log(\`BENCH campfire.meshes \${now.meshes}\`);"
		echo "		console.log(\`BENCH campfire.rebuildable \${now.rebuildable}\`);"
		echo "		console.log(\`BENCH campfire.pipelines \${now.pipelines}\`);"
		echo "		console.log(\`BENCH growth.drawItems \${now.drawItems - base.drawItems}\`);"
		echo "		console.log(\`BENCH growth.nodes \${now.nodes - base.nodes}\`);"
		echo "		console.log(\`BENCH growth.meshes \${now.meshes - base.meshes}\`);"
		echo "		console.log(\`BENCH growth.pipelines \${now.pipelines - base.pipelines}\`);"
		echo "		console.log(\`BENCH growth.uniforms \${now.uniforms - base.uniforms}\`);"
		echo "		console.log(\`BENCH growth.stack \${now.stack - base.stack}\`);"
		echo "		console.log(\`BENCH time.cpuMsPerFrame \${cpu / (MEASURED as float64)}\`);"
		echo "		console.log(\`BENCH time.wallMsPerFrame \${elapsed / (MEASURED as float64)}\`);"
		echo "		captureQuit();"
		echo "	}"
		echo "}"
		echo ""
		echo "configureCampfire(PixelArtSettings.full(), false);"
		echo "configureCampfireCamera(false, 0.0);"
		echo "voidRun(1280, 720, initCampfire, frame);"
	} > "$WORK/campfireBench.new"
	replace_if_changed "$WORK/campfireBench.new" "$CAPTURE/campfireBench.ms"
}

# ---- bench --------------------------------------------------------------------------------

# Counters gate hard and milliseconds only report. The counters here are the lengths of every
# piece of frame state, and a growth of anything but zero means a steady frame allocated —
# which "Frame state is preallocated... nothing in `frame` allocates" says it must not.
#
# There is deliberately no millisecond threshold. A wall-clock gate needs the run-to-run
# variance measured first, and a threshold tighter than that variance is a false alarm every
# other run, which ends with the gate being switched off. The number is printed so it can be
# watched; docs/VOID3D.md records the variance when it has been taken over enough runs.
run_bench() {
	if [ "${GATE_SKIP_BENCH:-0}" = "1" ]; then
		skip "bench: GATE_SKIP_BENCH=1 — frame-state growth was not measured"
		return
	fi
	if [ ! -f "$CAPTURE/campfireBench.ms" ]; then
		skip "bench: $CAPTURE/campfireBench.ms is missing"
		return
	fi
	if ! msc build "$CAPTURE/campfireBench.ms" --release > "$WORK/bench-build.log" 2>&1; then
		fail "bench: the bench entry did not build"
		tail -5 "$WORK/bench-build.log" | sed 's/^/         /'
		return
	fi
	if ! "./out/release/campfireBench.exe" > "$WORK/bench.log" 2>&1; then
		fail "bench: the bench run did not finish"
		tail -5 "$WORK/bench.log" | sed 's/^/         /'
		return
	fi
	rows=$(grep -c '^BENCH ' "$WORK/bench.log" || true)
	if [ "$rows" -eq 0 ]; then
		fail "bench: the run produced no BENCH rows"
		return
	fi
	grew=""
	for row in $(grep '^BENCH growth\.' "$WORK/bench.log" | awk '{print $2 "=" $3}'); do
		case "$row" in
			*=0) ;;
			*) grew="$grew $row" ;;
		esac
	done
	if [ -n "$grew" ]; then
		fail "bench: frame state grew during a steady run — the frame allocated:$grew"
		return
	fi
	cpu=$(grep '^BENCH time.cpuMsPerFrame' "$WORK/bench.log" | awk '{print $3}')
	wall=$(grep '^BENCH time.wallMsPerFrame' "$WORK/bench.log" | awk '{print $3}')
	counts=$(grep '^BENCH campfire\.' "$WORK/bench.log" | awk '{printf "%s=%s ", substr($2,10), $3}')
	pass "bench: no frame-state growth over $BENCH_FRAMES frames; $counts"
	note "bench: ${cpu} ms of CPU per frame; wall clock ${wall} ms is vsync-bound, not a cost"
	note "bench: reported only — docs/VOID3D.md records the variance behind any future threshold"
}

# ---- device -------------------------------------------------------------------------------

# The GLES3 backend is the one Hibernal ships on and the one with no byte-level numbers. It ran
# for the first time before M7 (tests/device/gles3Campfire.png) — on the Android emulator, which
# is not a device. This stage is a loud SKIP by default rather than a silent omission: a green
# gate should say out loud that the shipping backend is unverified here, the way the baseline
# skips do. GATE_DEVICE=1 builds, installs and runs it against whatever adb can see.
run_device() {
	if [ "${GATE_DEVICE:-0}" != "1" ]; then
		skip "device: GATE_DEVICE=1 not set — no GLES3 run this gate; every pixel claim here is D3D11 only"
		return
	fi
	adb=${ADB:-$HOME/AppData/Local/Android/Sdk/platform-tools/adb.exe}
	if [ ! -x "$adb" ] && ! command -v adb > /dev/null 2>&1; then
		skip "device: no adb (set ADB)"
		return
	fi
	[ -x "$adb" ] || adb=adb
	target=$("$adb" devices | awk 'NR>1 && $2=="device" { print $1; exit }')
	if [ -z "$target" ]; then
		skip "device: adb sees no device"
		return
	fi
	kind=$("$adb" -s "$target" shell getprop ro.build.characteristics | tr -d '')
	egl=$("$adb" -s "$target" shell getprop ro.hardware.egl | tr -d '')
	if ! "$adb" -s "$target" shell pidof com.metascript.voidsample > /dev/null 2>&1; then
		skip "device: $target ($kind, egl=$egl) is there but the app is not running — see tests/device/README.md"
		return
	fi
	"$adb" -s "$target" exec-out screencap -p > "$WORK/device.png" 2>/dev/null
	colours=$(magick "$WORK/device.png" -format "%k" info: 2>/dev/null || echo 0)
	if [ "$colours" -lt 100 ]; then
		fail "device: $target rendered $colours colours — a blank or near-blank frame"
		return
	fi
	pass "device: $target ($kind, egl=$egl) rendering, $colours colours — NOT a baseline comparison"
}

# ---- style --------------------------------------------------------------------------------

# CODE-STYLE section 16 caps a line at 100 columns with a tab counted as 4. The M5 review found
# five over-long lines and the M6 review found thirteen more, in the files M5 had just fixed. A
# finding that recurs the next milestone is infrastructure, not a third review comment.
#
# Scoped to what this port owns: src/void3d, its tests, and the campfire. void2d has its own
# gate and its own backlog.
STYLE_PATHS="src/void3d src/test/scene3dCheck.ms src/test/boundsCheck.ms src/test/meshDataCheck.ms src/test/drawCheck.ms"

run_style() {
	long=$(
		for path in $STYLE_PATHS; do
			find "$path" -name '*.ms' 2>/dev/null
		done | while read -r file; do
			expand -t 4 "$file" | awk -v f="$file" 'length($0) > 100 { print f ":" FNR " (" length($0) " cols)" }'
		done
	)
	if [ -n "$long" ]; then
		count=$(echo "$long" | grep -c .)
		fail "style: $count line(s) over 100 columns (CODE-STYLE section 16)"
		echo "$long" | head -8 | sed 's/^/         /'
		return
	fi
	pass "style: no line over 100 columns in $(echo $STYLE_PATHS | wc -w) path(s)"
}

# ---- allocation ---------------------------------------------------------------------------

# "Frame state is preallocated... nothing in `frame` allocates" (docs/VOID3D.md, Data types) is
# the one claim in this port that the bench stage cannot see: the bench gates the *lengths* of
# the frame state, and an allocation that does not change a length is invisible to it. That is
# exactly how M6 shipped a per-node `msArrayCopy` in `refresh` with a green gate — the copy trap
# of CODE-STYLE section 5, `const xs: Vec<T> = someStruct.field`, which copies and frees on
# every visit without moving any length.
#
# The M6 review found it by reading the emitted C, so that is what this checks. It is
# deterministic and it can fail, which is the whole point: a gate that cannot fail is worse than
# no gate. Runs after `tests`, which is what emits the C.
FRAME_PATH_FUNCTIONS="syncWorld collectDrawList refresh"

run_allocation() {
	emitted=$(ls -t out/debug/.cache/*scene_x_ms*.c 2>/dev/null | head -1)
	if [ -z "$emitted" ] || [ ! -f "$emitted" ]; then
		skip "allocation: no emitted C for scene.ms yet (the tests stage is what produces it)"
		return
	fi
	offenders=""
	for fn in $FRAME_PATH_FUNCTIONS; do
		copies=$(awk "/^[a-zA-Z_].*\y${fn}__M/,/^}/" "$emitted" | grep -c 'msArrayCopy' || true)
		[ "$copies" -gt 0 ] && offenders="$offenders ${fn}=${copies}"
	done
	if [ -n "$offenders" ]; then
		fail "allocation: the frame path copies an array — msArrayCopy in:$offenders"
		echo "         CODE-STYLE section 5, the copy trap: index the field or take a Span view"
		return
	fi
	pass "allocation: no msArrayCopy in the frame path ($FRAME_PATH_FUNCTIONS)"
}

# ---- pending ------------------------------------------------------------------------------

# tests/PENDING3D.md on rexa's rule: a listed case that stops holding fails the run, and its row
# is deleted in the same commit as the fix. Enforced in both directions, because a list with a
# forcing function in only one direction rots from the other end.
run_pending() {
	if [ ! -f "$PENDING" ]; then
		skip "pending: $PENDING is missing, so nothing holds the known divergences to account"
		return
	fi
	rows=$(grep -oE '^\| `[a-z0-9-]+`' "$PENDING" | tr -d '|` ' | sort)
	tags=$(grep -rhoE 'PENDING3D: [a-z0-9-]+' src/ | sed 's/PENDING3D: //' | sort -u)
	graduated=""
	for row in $rows; do
		case "$row" in
			baselines-adopted-circular)
				grep -q 'plausible\* M4 images' docs/VOID3D.md || graduated="$graduated $row" ;;
			gles3-emulator-only)
				grep -q 'not a device' docs/VOID3D.md || graduated="$graduated $row" ;;
			*)
				echo "$tags" | grep -qx "$row" || graduated="$graduated $row" ;;
		esac
	done
	unlisted=""
	for tag in $tags; do
		echo "$rows" | grep -qx "$tag" || unlisted="$unlisted $tag"
	done
	if [ -n "$graduated" ]; then
		fail "pending: listed but no longer holding — delete the row in the commit that fixed it:$graduated"
		return
	fi
	if [ -n "$unlisted" ]; then
		fail "pending: marked in the tree with no row in $PENDING:$unlisted"
		return
	fi
	count=$(echo "$rows" | grep -c .)
	pass "pending: $count rows in $PENDING, every sentinel present and every sentinel listed"
}

# ---- tests --------------------------------------------------------------------------------

run_tests() {
	if [ ! -f "$TMP/test2d.ms" ]; then
		skip "tests: $TMP/test2d.ms is missing (one line: import \"../../src/test/index\")"
		return
	fi
	if msc test "$TMP/test2d.ms" > "$WORK/tests.log" 2>&1; then
		summary=$(grep -E '^ *Tests ' "$WORK/tests.log" | tail -1 | tr -s ' ')
		if grep -qE 'failed' "$WORK/tests.log"; then
			fail "tests:$summary"
			grep -nE 'failed|FAIL' "$WORK/tests.log" | head -20
		else
			pass "tests:$summary"
		fi
	else
		fail "tests: msc test exited nonzero"
		tail -30 "$WORK/tests.log"
	fi
}

# ---- capture ------------------------------------------------------------------------------
#
# One configuration: rebuild the entry, run it, and cmp all four frames against the baseline it
# claims to reproduce. The binary is deleted first so the link is always redone; the object
# eviction above is what makes a stale shader impossible.
run_capture() {
	name=$1
	baseline=$2
	what=$3
	entry=$CAPTURE/$name.ms
	if [ ! -f "$entry" ]; then
		fail "capture $name: the entry is missing"
		return
	fi
	rm -f "out/debug/$name.exe"
	if ! msc build "$entry" > "$WORK/$name.build.log" 2>&1; then
		fail "capture $name: build failed"
		tail -30 "$WORK/$name.build.log"
		return
	fi
	if [ ! -f "out/debug/$name.exe" ]; then
		fail "capture $name: out/debug/$name.exe was not produced"
		return
	fi
	rm -f "$CAPTURE/gate/${name}_"*.ppm
	if ! CAPTURE_PREFIX="$CAPTURE/gate/$name" "./out/debug/$name.exe" > "$WORK/$name.run.log" 2>&1; then
		fail "capture $name: the run exited nonzero"
		tail -20 "$WORK/$name.run.log"
		return
	fi
	missing=0
	differing=0
	adopted=0
	for frame in $FRAMES; do
		got=$CAPTURE/gate/${name}_$frame.ppm
		want=$CAPTURE/${baseline}_$frame.ppm
		if [ ! -f "$got" ]; then
			fail "capture $name: frame $frame was not captured"
			return
		fi
		if [ ! -f "$want" ]; then
			if [ "${GATE_ADOPT:-0}" = "1" ]; then
				cp "$got" "$want"
				adopted=$((adopted + 1))
			else
				missing=$((missing + 1))
			fi
			continue
		fi
		if ! cmp -s "$got" "$want"; then
			differing=$((differing + 1))
			note "capture $name: frame $frame differs from $want"
			if command -v magick > /dev/null 2>&1; then
				absolute=$(magick compare -metric AE "$want" "$got" null: 2>&1 | tail -1)
				peak=$(magick compare -metric PAE "$want" "$got" null: 2>&1 | tail -1)
				note "capture $name: frame $frame AE $absolute, PAE $peak"
			fi
		fi
	done
	if [ "$differing" -gt 0 ]; then
		fail "capture $name ($what): $differing of 4 frames differ from ${baseline}_*.ppm"
	elif [ "$missing" -gt 0 ]; then
		skip "capture $name ($what): $missing of 4 baselines ${baseline}_*.ppm missing — built and rendered, compared nothing (GATE_ADOPT=1 adopts)"
	elif [ "$adopted" -gt 0 ]; then
		skip "capture $name ($what): adopted $adopted of 4 baselines as ${baseline}_*.ppm from this run — write down what was replaced and why"
	else
		pass "capture $name ($what): 4 frames byte-identical to ${baseline}_*.ppm"
	fi
}

run_captures() {
	if [ "${GATE_SKIP_CAPTURE:-0}" = "1" ]; then
		skip "capture: GATE_SKIP_CAPTURE=1 — the seven configurations were not built, not run, not compared"
		return
	fi
	if [ ! -f "$CAPTURE/capture.c" ] || [ ! -f "$CAPTURE/capture.h" ]; then
		skip "capture: $CAPTURE/capture.c and capture.h are missing (the D3D11 readback harness lives in gitignored out/tmp)"
		return
	fi
	purge_stale_shader_objects
	run_capture campfireCapture        before     "palette off"
	run_capture campfirePaletteCapture m3palette  "palette on"
	run_capture campfirePreviewCapture m3preview  "preview"
	run_capture campfireDirectCapture  m3direct   "postPass off"
	run_capture campfireDepthCapture   m3depth    "DepthTexture"
	run_capture campfireRebuildCapture before     "rebuilt mid-run"
	run_capture campfireSpinCapture    m6spin     "log group turning"
}

# ---- manifest -----------------------------------------------------------------------------

MANIFEST=docs/baselines3d.sha256
PENDING=tests/PENDING3D.md
BENCH_WARMUP=${GATE_BENCH_WARMUP:-30}
BENCH_FRAMES=${GATE_BENCH_FRAMES:-300}

baseline_files() {
	for prefix in before m3palette m3preview m3direct m3depth m6spin; do
		for frame in $FRAMES; do
			echo "$CAPTURE/${prefix}_$frame.ppm"
		done
	done
}

run_manifest() {
	missing=0
	for file in $(baseline_files); do
		[ -f "$file" ] || missing=$((missing + 1))
	done
	if [ "$missing" -gt 0 ]; then
		skip "manifest: $missing of 24 baselines are missing, nothing to check them against"
		return
	fi
	# Hashes are over the basename, so the manifest does not carry this checkout's path.
	( cd "$CAPTURE" && sha256sum $(baseline_files | sed "s|$CAPTURE/||") ) > "$WORK/manifest.new" 2>/dev/null
	if [ "${GATE_WRITE_MANIFEST:-0}" = "1" ]; then
		cp "$WORK/manifest.new" "$MANIFEST"
		skip "manifest: rewrote $MANIFEST from this run — commit it with the re-baselining it records"
		return
	fi
	if [ ! -f "$MANIFEST" ]; then
		skip "manifest: $MANIFEST is missing (GATE_WRITE_MANIFEST=1 writes it)"
		return
	fi
	# core.autocrlf hands the committed manifest back with CRLF while sha256sum always writes
	# LF, so the two are compared with the line endings stripped: the claim is about the
	# hashes, not about how this checkout stores a text file.
	tr -d '\r' < "$MANIFEST" > "$WORK/manifest.committed"
	if diff -q "$WORK/manifest.committed" "$WORK/manifest.new" > /dev/null 2>&1; then
		pass "manifest: 24 baselines match $MANIFEST"
	else
		fail "manifest: the baselines on disk are not the ones $MANIFEST records"
		diff "$WORK/manifest.committed" "$WORK/manifest.new" | head -12
	fi
}

# ---- android ------------------------------------------------------------------------------

run_android() {
	if [ "${GATE_SKIP_ANDROID:-0}" = "1" ]; then
		skip "android: GATE_SKIP_ANDROID=1 — the arm64 .so was not built"
		return
	fi
	entry=$TMP/android/campfireEntry.ms
	if [ ! -f "$entry" ]; then
		skip "android: $entry is missing"
		return
	fi
	ndk=${ANDROID_NDK:-$HOME/AppData/Local/Android/Sdk/ndk/28.0.13004108}
	cc=$ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
	if [ ! -f "$cc" ]; then
		skip "android: no NDK clang at $cc (set ANDROID_NDK)"
		return
	fi
	if msc build "$entry" --os=android --app=lib \
		--cc="$cc --target=aarch64-linux-android26" \
		--output="$TMP/android/libVoidAndroid.so" > "$WORK/android.log" 2>&1; then
		pass "android: arm64 libVoidAndroid.so built, $(wc -c < "$TMP/android/libVoidAndroid.so") bytes"
	else
		fail "android: the arm64 build failed"
		tail -30 "$WORK/android.log"
	fi
}

# ---- run ----------------------------------------------------------------------------------

echo "void3d gate"
echo "  msc      $(msc --version 2>&1 | sed 's/\x1b\[[0-9;]*m//g' | tr -d '\r\n')"
echo "  commit   $(git rev-parse --short HEAD 2>/dev/null) on $(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
echo

if prepare_scene; then
	prepare_entries
	pass "prepare: campfireScene.ms and the seven capture entries are current"
else
	fail "prepare: the capture entries were not written"
fi
run_entries
run_pending
run_tests
run_captures
run_manifest
run_allocation
run_style
run_device
run_bench
run_android

echo
if [ "$FAILURES" -gt 0 ]; then
	echo "GATE FAILED — $FAILURES failing stage(s), $SKIPPED skipped"
	exit 1
fi
if [ "$SKIPPED" -gt 0 ]; then
	echo "GATE GREEN with $SKIPPED skipped stage(s) — read the SKIP lines before trusting this"
	exit 0
fi
echo "GATE GREEN"
