#!/bin/sh
# The Heaps oracle. Heaps is the reference implementation for everything this repo ports, so a
# claim about what Heaps does should be a measurement, not a citation. Before this existed,
# docs/VOID3D.md said things like "Heaps answers -2e20 per axis (Bounds.hx:329)" on the strength
# of somebody having read the file.
#
# Shape, taken from rexa: cases are data rows with no expected output; `regen` replays them
# through real Heaps and writes a snapshot; an ordinary `check` diffs the port against that
# snapshot and never needs Haxe installed. Intentional divergences are declared on the case and
# cross-referenced to tests/PENDING3D.md, and they are checked in *both* directions — a case
# marked as diverging that starts agreeing fails the run, exactly as a PENDING row does.
#
# Not h3d-specific on purpose. void2d will want the same harness against h2d for its own
# oracle, so everything language- and library-specific lives in the case file, not here.
#
#   sh scripts/oracle.sh check  tests/oracle/bounds3d.cases     # no Haxe needed
#   sh scripts/oracle.sh regen  tests/oracle/bounds3d.cases     # needs Haxe + heaps
#
# Environment:
#   HAXE_BIN, NEKO_DIR   where scoop put them (defaults below)
#   ORACLE_KEEP=1        leave the generated programs in out/tmp/oracle for reading
set -eu

cd "$(dirname "$0")/.."
MODE=${1:-check}
CASES=${2:-tests/oracle/bounds3d.cases}
WORK=out/tmp/oracle
mkdir -p "$WORK"

[ -f "$CASES" ] || { echo "oracle: no case file at $CASES" >&2; exit 2; }
SNAPSHOT=$(dirname "$CASES")/$(basename "$CASES" .cases).snapshot

# ---- the case file --------------------------------------------------------------------------
# Directives are `# key: value` lines; a case opens with `case <id> [tol=<n>] [diverges=<row>]`
# and its two bodies are the `haxe>` and `ms>` lines under it. Both bodies end by calling
# `emit(id, ...)`, which each side defines. Heaps' `emit` takes an array; the port's side has
# one helper per value count (`emit1`, `emit3`, `emit4`, `emit9`, `emitB`), and the two sides of
# a case must emit the same number of values or the row silently mismatches.

directive() { sed -n "s|^# $1: ||p" "$CASES" | head -1; }

LIBS=$(directive lib)
HAXE_PRELUDE=$(sed -n 's|^# haxe-prelude: ||p' "$CASES")
MS_PRELUDE=$(sed -n 's|^# ms-prelude: ||p' "$CASES")
# Statements the port's side runs at the top of `main`, before the first case: setup shared by
# every case in the file, where a prelude line can only declare.
MS_MAIN_PRELUDE=$(sed -n 's|^# ms-main-prelude: ||p' "$CASES")

case_ids() { sed -n 's|^case \([a-z0-9-]*\).*|\1|p' "$CASES"; }
case_attr() { sed -n "s|^case $1 .*$2=\([^ ]*\).*|\1|p" "$CASES" | head -1; }
case_body() { awk -v id="$1" -v tag="$2" '
	$1 == "case" { active = ($2 == id) }
	active && index($0, tag "> ") == 1 { print substr($0, length(tag) + 3) }
' "$CASES"; }

# ---- regen: replay the cases through real Heaps ---------------------------------------------

regen() {
	HAXE=${HAXE_BIN:-$HOME/scoop/shims/haxe}
	NEKO=${NEKO_DIR:-$HOME/scoop/apps/neko/current}
	command -v "$HAXE" > /dev/null 2>&1 || { echo "oracle: no haxe at $HAXE" >&2; exit 2; }
	PATH="$NEKO:$PATH"
	export PATH
	HAXE_VERSION=$("$HAXE" --version 2>&1 | head -1)
	HEAPS_DIR=$(haxelib path heaps 2>/dev/null | head -1 | sed 's/\r$//')
	HEAPS_PIN=$(git -C "$HEAPS_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)

	{
		echo "$HAXE_PRELUDE"
		echo 'class Oracle {'
		echo '	static function emit(id: String, vs: Array<Float>) {'
		echo '		var parts = [];'
		echo '		for (v in vs) parts.push(Std.string(v));'
		echo '		untyped console.log("CASE " + id + " " + parts.join(" "));'
		echo '	}'
		echo '	static function main() {'
		for id in $(case_ids); do
			echo "		// $id"
			case_body "$id" haxe | sed 's|^|		|'
		done
		echo '		js.Syntax.code("process.exit(0)");'
		echo '	}'
		echo '}'
	} > "$WORK/Oracle.hx"

	libs=""
	for lib in $LIBS; do libs="$libs -lib $lib"; done
	# shellcheck disable=SC2086
	( cd "$WORK" && "$HAXE" -js oracle.js -main Oracle $libs -D js-es=6 ) || {
		echo "oracle: haxe failed; see $WORK/Oracle.hx" >&2; exit 1; }

	# Write to a file, never a pipe: a killed node run loses buffered stdout and reads as a hang
	# (docs/SCENE-SCALE.md, "Reproducing").
	timeout "${ORACLE_TIMEOUT:-120}" node --max-old-space-size=8192 "$WORK/oracle.js" 		> "$WORK/heaps.out" 2>&1 || {
		status=$?
		[ "$status" = 124 ] && echo "oracle: node did not exit within ${ORACLE_TIMEOUT:-120}s" >&2
		echo "oracle: node failed ($status); see $WORK/heaps.out" >&2; exit 1; }

	{
		echo "# Generated by scripts/oracle.sh regen $CASES — do not edit by hand."
		echo "# Real Heaps, run through node. Heaps commit and toolchain at the time of writing:"
		echo "#   heaps $HEAPS_PIN, haxe $HAXE_VERSION, node $(node --version)"
		echo "# Heaps computes in float64 and this port in float32, so every case carries a tol."
		grep '^CASE ' "$WORK/heaps.out" | sed 's|^CASE ||'
	} > "$SNAPSHOT"
	echo "oracle: wrote $SNAPSHOT ($(grep -c . "$SNAPSHOT") lines)"
}

# ---- check: run the port's side and diff against the snapshot -------------------------------

check() {
	[ -f "$SNAPSHOT" ] || { echo "oracle: no snapshot at $SNAPSHOT (run regen)" >&2; exit 2; }
	{
		echo "$MS_PRELUDE"
		echo 'function emit1(id: string, a: float32): void { console.log(`CASE ${id} ${a}`); }'
		echo 'function emit3(id: string, a: float32, b: float32, c: float32): void {'
		echo '	console.log(`CASE ${id} ${a} ${b} ${c}`);'
		echo '}'
		echo 'function emitB(id: string, a: boolean): void {'
		echo '	console.log(`CASE ${id} ${a ? 1.0 : 0.0}`);'
		echo '}'
		echo 'function emit4(id: string, a: float32, b: float32, c: float32, d: float32): void {'
		echo '	console.log(`CASE ${id} ${a} ${b} ${c} ${d}`);'
		echo '}'
		echo 'function emit9('
		echo '	id: string,'
		echo '	a: float32, b: float32, c: float32,'
		echo '	d: float32, e: float32, f: float32,'
		echo '	g: float32, h: float32, i: float32,'
		echo '): void {'
		echo '	console.log(`CASE ${id} ${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i}`);'
		echo '}'
		echo 'function main(): int32 {'
		echo "$MS_MAIN_PRELUDE"
		for id in $(case_ids); do
			echo "	// $id"
			case_body "$id" ms | sed 's|^|	|'
		done
		echo '	return 0;'
		echo '}'
		echo 'main();'
	} > "$WORK/oracleCheck.ms"

	msc build "$WORK/oracleCheck.ms" > "$WORK/build.log" 2>&1 || {
		echo "oracle: the port's side did not build; see $WORK/build.log and $WORK/oracleCheck.ms" >&2
		tail -12 "$WORK/build.log" >&2; exit 1; }
	./out/debug/oracleCheck.exe > "$WORK/port.out" 2>&1 || {
		echo "oracle: the port's side did not run; see $WORK/port.out" >&2; exit 1; }

	grep '^CASE ' "$WORK/port.out" | sed 's|^CASE ||' > "$WORK/port.rows"

	failures=0
	for id in $(case_ids); do
		want=$(grep "^$id " "$SNAPSHOT" | head -1 | cut -d' ' -f2-)
		got=$(grep "^$id " "$WORK/port.rows" | head -1 | cut -d' ' -f2-)
		tol=$(case_attr "$id" tol); tol=${tol:-1e-6}
		row=$(case_attr "$id" diverges)
		if [ -z "$want" ]; then
			echo "MISSING  $id — not in the snapshot; regen after adding a case"
			failures=$((failures + 1)); continue
		fi
		if [ -z "$got" ]; then
			echo "MISSING  $id — the port emitted nothing"
			failures=$((failures + 1)); continue
		fi
		agree=$(AGREE_WANT="$want" AGREE_GOT="$got" AGREE_TOL="$tol" python -c '
import os, sys
w = os.environ["AGREE_WANT"].split()
g = os.environ["AGREE_GOT"].split()
t = float(os.environ["AGREE_TOL"])
if len(w) != len(g):
    print("no"); sys.exit()
for a, b in zip(w, g):
    a, b = float(a), float(b)
    scale = max(1.0, abs(a))
    if abs(a - b) > t * scale:
        print("no"); sys.exit()
print("yes")
')
		if [ -n "$row" ]; then
			if [ "$agree" = "yes" ]; then
				echo "GRADUATED $id — declared as diverging from Heaps ($row) but now agrees:"
				echo "          heaps $want"
				echo "          port  $got"
				echo "          reconcile tests/PENDING3D.md row '$row' in the commit that changed this"
				failures=$((failures + 1))
			else
				echo "DIVERGES  $id — as declared ($row): heaps [$want] port [$got]"
			fi
		else
			if [ "$agree" = "yes" ]; then
				echo "AGREES    $id"
			else
				echo "MISMATCH  $id — undeclared divergence from Heaps:"
				echo "          heaps $want"
				echo "          port  $got"
				echo "          if deliberate, add diverges=<row> to the case and a row to PENDING3D"
				failures=$((failures + 1))
			fi
		fi
	done

	total=$(case_ids | grep -c .)
	[ "${ORACLE_KEEP:-0}" = "1" ] || rm -f "$WORK/oracleCheck.ms"
	if [ "$failures" -gt 0 ]; then
		echo "oracle: $failures of $total case(s) failed"
		return 1
	fi
	echo "oracle: $total case(s) against real Heaps, all as declared"
}

case "$MODE" in
	regen) regen ;;
	check) check ;;
	*) echo "usage: sh scripts/oracle.sh [check|regen] <cases-file>" >&2; exit 2 ;;
esac
